### ISSUE TITLE
Sign not preserved although precision specified?

### ISSUE THREAD

**Issue by milankl** [LLNL/zfp#101]
I want to compress some float32 arrays with zfp, the original values are small (1e-13 to 1e-9), let's mimic that by
```python
In [77]: A = np.random.rand(1000,1000).astype(np.float32)*1e-8                  
```
then compress&decompress by specifying precision (presumably between 7-16 mantissa bits should be preserved in my application)
```python
In [79]: Ac = zfpy.compress_numpy(A,precision=7);                               
In [80]: A2 = zfpy.decompress_numpy(Ac);
```
However, the compression (or decompression) does not seem to preserve the sign for about 3% of the values:
```python
In [84]: np.sum(A2 < 0)                                                         
Out[84]: 28341

In [85]: np.sum(A2 < 0)/A2.size                                                 
Out[85]: 0.028341
```
Am I doing something wrong or is the sign not guaranteed?

**Comment by lindstro** [comment]
In fixed-precision mode, zfp makes no guarantees on the sign.  Note that setting `precision=7` does not mean that values will be accurate to seven bits of precision; see this [FAQ](https://zfp.readthedocs.io/en/develop/faq.html#q-relerr).

If you want to preserve the sign and some number of bits of precision, you can achieve that using the expert mode settings discussed in this FAQ, though the zfpy Python interface does not yet support this mode; you'll have to use the C API.  However, you may truncate the floating-point values yourself and then invoke zfpy's reversible (lossless) mode.

**Comment by milankl** [comment]
Thanks Peter! Yeah, a sign-switch is unfortunately a no-go for my application, although in most cases I'm dealing with only positive data anyway. Just rounding to the nth significant bit manually and then using lossless sounds like a good approach - I will try that!
