### ISSUE TITLE
install bug when used as a submodule

### ISSUE THREAD

**Issue by rgclapp007** [LLNL/zfp#108]
zfp now fails to install as a submodule. The line
  configure_file(CMakeLists.txt.in googletest-download/CMakeLists.txt)
needs to be
  configure_file(CMakeLists.txt.in ${CMAKE_BINARY_DIR}/googletest-download/CMakeLists.txt)

**Comment by lindstro** [comment]
Thanks for the suggestion, but this line appears on the develop branch only, which should not be used for purposes other than zfp development.  If you want to install zfp, please use the master branch or one of the tagged release branches.
