### ISSUE TITLE
Largest possible array size

### ISSUE THREAD

**Issue by milankl** [LLNL/zfp#115]
Probably just a quick clarification needed: I'm running into problems when compressing arrays of size 14GB. In the documentation I found "array dimensions are otherwise limited only by the size of an unsigned integer.", which sounds like the [error that I'm getting](https://github.com/milankl/ZfpCompression.jl/issues/9). 
- in practice should I use arrays of max size a few GB, and
- the compression factors won't change when I split up arrays in a given dimension in chunks of 4, right?

**Comment by lindstro** [comment]
The short answer is yes, but let me elaborate.

There are various array size limitations in zfp 0.5.5 dependent on the functionality exercised and whether you're referring to the zfp high-level C API (`zfp_compress` and friends) or to zfp's compressed-array classes (`zfp::array`, `cfp_array`).  Judging by your error, I'm assuming you're referring to the high-level API.

- The C implementation of `zfp_compress` supports 64-bit array dimensions and arrays with up to 2^64 elements (though the CUDA implementation currently does not).  However, the `zfp_field` struct passed to `zfp_compress` uses 32-bit unsigned integers to specify array dimensions, which ultimately limit each array dimension to 2^32 elements.
- The optional header supports dimensions up to 2^(48 / d) for d-dimensional arrays.  `zfp_write_header` fails if the dimensions exceed this limit.
- The compressed-array classes use 32-bit unsigned integers to specify array dimensions.  This limitation will be lifted in the next zfp release, and has already been removed on the current `develop` branch.

Let me also point out that if your data is correlated in more than one dimension, then you should by all means compress it as a multidimensional array to obtain substantial improvements in compression ratio.  This should also alleviate any array size limitations.

To answer your second question, yes, you may partition d-dimensional arrays into chunks of 4^d values without impacting the compression ratio, modulo the very small overhead of any optional headers and 64-bit word alignment that occurs at the end of the compressed stream.

**Comment by milankl** [comment]
Amazing answer, Peter, thanks. I was using float32 arrays of size 1800x901x91x25, so that shouldn't conflict your points 1-3, I might have done something wrong in the Julia wrapper then. 

I'm getting an bufsize Int64 from `zfp_stream_maximum_size` and then pass that on to `stream_open` which takes a uint32, the error is raised when the bufsize int64 is truncated to a uint32. In probably have misinterpreted the arguments of some function calls here. Will look into this next week.

**Comment by lindstro** [comment]
The C function `stream_open` takes a `size_t`, not `uint32`.  Are you perhaps talking about the Julia wrapper?  Either way, I suspect this is not the issue as the buffer size argument passed to `stream_open` is essentially ignored.

**Comment by milankl** [comment]
Sorry, that was my bad, yes, `stream_open` now takes a `size_t`/`Int64` in the Julia wrapper too, that was the cause for my error. Corrected in ZfpCompression.jl v0.1.1
