### ISSUE TITLE
CUDA tests failing after building with -DZFP_WITH_CUDA ON

### ISSUE THREAD

**Issue by shauryapatel1995** [LLNL/zfp#116]
Hi, 
I am trying to use zfp to perform compression on the gpu but it seems that zfp is not working for my environment with cuda. The cuda version I am using is 11.1.

A result from the test suite, all the relevant tests are failing - 
```
Test #114: testZfpCuda3dFloat ..................***Failed    2.28 sec
Start 115: testZfpSerial3dDouble
```

**Comment by shauryapatel1995** [comment]
Another issue is that even though I build zfp with 11.1 it still gives me this warning "/usr/bin/ld: warning: libcudart.so.7.5, needed by libzfp.so, may conflict with libcudart.so.11.0" I am not sure if this might be relevant.

**Comment by lindstro** [comment]
Sounds like you're picking up the wrong binary of the CUDA runtime.  What platform are you on?  If Linux, what does `ldd bin/zfp` say?  Might also be useful to see what `ctest -R Cuda -V` reports.

**Comment by shauryapatel1995** [comment]
Hi @lindstro thanks for the reply, I will run these today and let you know today about these results. I have a feeling it is related to the wrong binary being picked up because the PATH variable shows both cuda11 and cuda7.5 in path, I also set the bin path for cmake but it's still giving a problem.

**Comment by shauryapatel1995** [comment]
linux-vdso.so.1 =>  (0x00002aaaaaacd000)
        libzfp.so.0 => lib64/libzfp.so.0 (0x00002aaaaaccf000)
        libm.so.6 => /lib64/libm.so.6 (0x00002aaaaafd7000)
        libc.so.6 => /lib64/libc.so.6 (0x00002aaaab2d9000)
        libgomp.so.1 => /lib64/libgomp.so.1 (0x00002aaaab6a7000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00002aaaab8cd000)
        libcudart.so.7.5 => /lib64/libcudart.so.7.5 (0x00002aaaabae9000)
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00002aaaabd47000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00002aaaac04e000)
        /lib64/ld-linux-x86-64.so.2 (0x00002aaaaaaab000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00002aaaac264000)
        librt.so.1 => /lib64/librt.so.1 (0x00002aaaac468000)

The library being picked up is definitely wrong, I updated the bin part for cuda and also during the build process it does pick up the correct path but maybe because of cmake its picking up this version of cuda?

**Comment by shauryapatel1995** [comment]
Example of cmake report - 
```
 Environment variable CUDA_ROOT is set to:

    /cm/shared/apps/cuda11/11.1.0/
```

**Comment by lindstro** [comment]
I think the relevant environment variable is CUDAToolkit_ROOT; see https://cmake.org/cmake/help/latest/module/FindCUDAToolkit.html#module:FindCUDAToolkit.  For older versions of CMake, see https://cmake.org/cmake/help/latest/module/FindCUDA.html.

**Comment by shauryapatel1995** [comment]
I removed cuda7.5 from path and it fixed the issue! Thanks for your help!
