### ISSUE TITLE
Javascript (browser side) support

### ISSUE THREAD

**Issue by abohara** [LLNL/zfp#117]
Increasingly, browser based (web) UI apps are handling larger numerical arrays (passed from the server side) that could benefit from zfp compression (&serialization). Any plans to make zfp available (browser/js) side. For e.g. a lightweight javascript implementation or js wrapper around a webassembly module (compiled from current C)?

**Comment by lindstro** [comment]
No current plans, but we'd appreciate contributions from the community.

**Comment by abohara** [comment]
Thanks @lindstro ! Do you have any thoughts on what would be the most viable first step towards making zfg available browser side?  i.e. compilation to webassembly or lightweight javascript implementation ? Any other paths you foresee ?

**Comment by lindstro** [comment]
I'm afraid this is not my forte.  I don't do webassembly or javascript, and don't feel qualified to comment.  Sorry.

**Comment by abohara** [comment]
Thanks @lindstro . I will investigate this further and close the issue till I have a concrete way forward.
