### ISSUE TITLE
Missing install target for utility

### ISSUE THREAD

**Issue by confluence** [LLNL/zfp#122]
If `BUILD_UTILITIES` is enabled, the `zfp` executable is built, but it is not installed to the appropriate system `bin` directory, as I would expect. Adding this install target to `CMakeLists.txt` produces the expected result:

    if(BUILD_UTILITIES)
        install(FILES
        "${PROJECT_BINARY_DIR}/${CMAKE_INSTALL_BINDIR}/zfp"
        DESTINATION "${CMAKE_INSTALL_BINDIR}")
    endif()

Would it be possible to add this? I'm not sure if these are the best variables to use to determine the correct paths.

**Comment by lindstro** [comment]
This is indeed an issue that we recently discovered while updating the zfp Spack package and will fix in the next release.  Thanks for reporting it.  I'll keep this issue open until it has been resolved.

**Comment by lindstro** [comment]
The suggested addition works on Linux but not on Windows, which uses a different directory structure (e.g., `bin/Release`) and executable name (`zfpcmd.exe`).  We'd welcome any suggestions on how to correctly implement this on Windows.

**Comment by confluence** [comment]
Ah. That's outside my field of expertise, I'm afraid -- I only build software for Linux and sometimes MacOS.

**Comment by lindstro** [comment]
This was actually easier than I thought.  This does the trick:

```
if(BUILD_UTILITIES)
  install(TARGETS zfpcmd
    DESTINATION "${CMAKE_INSTALL_BINDIR}")
endif()
```

I've pushed a fix on `develop`.

**Comment by lindstro** [comment]
I spoke too soon.  For some reason, this addition (which works on our systems) is rejected by Travis CI.  Our Travis logs are also mysteriously missing from CDash, so I have no way of telling what's going wrong.  For now, I've re-opened the issue.

**Comment by lindstro** [comment]
Older versions of cmake (as used by Travis) evidently do not search subdirectories for targets.  After moving the install command to the utils subdirectory, things are finally working.  The fix has been pushed to `develop`, which resolves this issue.
