### ISSUE TITLE
OpenMP compression + serial decompression fails for large data

### ISSUE THREAD

**Issue by data-panda** [LLNL/zfp#125]
Team, We just found another bug which happens in the case of OpenMP compression and Serial Decompression (reproducible with zfp 0.5.5 release AND `develop` branch) with large data (>512^3) and num threads >= 4. Here are the numbers that we obtained for a float dataset of size 768^3

| run ID | data size (n^3) | data type | compression ratio | serial   | omp compression(4 threads) |
| ------ | --------------- | --------- | ----------------- | -------- | -------------------------- |
|        |                 |           |                   |          |                            |
| 1      | 768^3           | float     | 2                 | 2.61E-05 | 23.5862                    |
| 2      | 768^3           | float     | 4                 | 5.65E-03 | 5.65E-03                   |
| 3      | 768^3           | float     | 8                 | 1.15E-01 | 1.15E-01                   |

This happens only at `set OMP_THREAD_NUM=4` and beyond (pure CPU run). 

The above numbers can be reproduced with this code gist: https://gist.github.com/data-panda/1f164852fbdadc7364f5cdf8a82ab065  (notice at line 155: openMP compression and line 168: serial decompression)

compile: `icc -O3 -fopenmp simple_0bug_reproducer.c -lm -lzfp`

**Comment by lindstro** [comment]
Thanks for reporting this bug.  Unfortunately, I am not able to reproduce it.  Are you sure that the rates match between compression and decompression?  For future reference, note that the rate is a `double`, not an `int`.  Also, when submitting bug reports, we'd appreciate if the code reproducing the bug can be compiled once as a single program without requiring manual code edits (e.g., to change the rate, execution mode, number of threads, ...) to reproduce the bug.

In spite of not being able to reproduce the issue, I do see that there are potential problems in the OpenMP implementation for much larger arrays (>= 2 G array elements).  There are several computations that should be done using 64- instead of 32-bit integers.  I will update this code and push a fix to `develop`.  Perhaps that will address your issue.

**Comment by data-panda** [comment]
@lindstro thanks very much for your comment. Maybe I overlooked something while giving the link to the reproducer code. Apologies!

Please try this gist: https://gist.github.com/data-panda/5b37c2823eb57696577105708875a721

Compile: `icc -fopenmp -O3 omp_768_cr_2.c -lm -lzfp`

Run1:
```
export OMP_NUM_THREADS = 2
./a.out
```

Run2:
```
export OMP_NUM_THREADS = 4
./a.out
```
You should observe the following rmse's:
run 1: `2.610459e-05` 
run 2: `2.358627e+01`

Here is the serial compression and decompression gist: https://gist.github.com/data-panda/93d3ad48e098ade08f4154b016527dd3

Compile: `icc -fopenmp -O3 serial_768_cr_2.c -lm -lzfp`
Run: `./a.out`

You should observe this rmse with serial compression and decompression at CR 2: `2.610459e-05`

This is all with a `double` bits_per_value of 16.0 (resulting in a CR of 2.0). So `int` to `double` conversion is not helping + thanks for pointing that the rate must go as double.

**Comment by lindstro** [comment]
I can now reproduce this issue.  I think I earlier may have used a zfp library that was compiled without OpenMP enabled (gotta check the return value of `zfp_stream_set_execution`).

I feel reasonably confident that this will be an easy bug to identify and fix.  I'll keep you updated on our progress.

**Comment by lindstro** [comment]
Good news--it looks like the issue can be narrowed down to a single line of code: https://github.com/LLNL/zfp/blob/f668af3d54c52bec96ae94b2b631b1335d3704b5/src/share/parallel.c#L56.  Here `block * stream->maxbits` is computed as a 32-bit integer that can overflow when the start block for a given thread is large (the more threads you use, the larger the first block ID of the last thread is).  Changing the type of `block` to `size_t` fixes the problem in your example.

Looking over this code, additional changes are needed to address similar bugs that may occur with even larger arrays.  I will update this code and push a fix to `develop` in the next day or two.

**Comment by data-panda** [comment]
Great Peter 🥳! We had a hint that, this is again linked with integer overflow. Will stay tuned to pull all those data type upgradations when you push the code changes. Meanwhile, I will change the line mentioned by you and test it out a bit.

**Comment by lindstro** [comment]
The OpenMP bug has been fixed on `develop`.  Please reopen if this does not address your issue.
