### ISSUE TITLE
New release in 2021

### ISSUE THREAD

**Issue by hmaarrfk** [LLNL/zfp#143]
Hello,

We are trying to create a release on conda forge for windows + PyPy support .

A recent pull request https://github.com/LLNL/zfp/pull/109

was accepted in 2020 for PyPy compatibility but is causing us headaches patching with regards to patching.

Are you able to make an official release, even if it is just a patch version, for 2021?

Best,

Mark

**Comment by lindstro** [comment]
We're planning on a release in the coming weeks.  I know I've said this before, but we're getting awfully close.  Please let us know if any changes need to go into this release and we'll incorporate them.

**Comment by siebrenreker** [comment]
Is there any update on this status or is there something we can do to help push towards a new release?

**Comment by lindstro** [comment]
We're done adding new features and are finishing up a few missing tests, documentation, and minor issues with installation.  Should not be long now, though we'll be taking time off over the holidays, so the release won't happen until after new year.

We could in fact use some help with a couple of items:

- Issue #150 needs to be resolved, having to do with ensuring that cmocka gets built using the same configuration (Release or Debug) as zfp, which is required by Windows.  Using recent versions of CMake, the tests currently don't build on macOS.
- CMake will currently install zfpy.so under ${CMAKE_INSTALL_PREFIX}/lib/python3.x/site-packages.  I'm not sure this is where we want it.  I know we had some issues with getting zfpy installed properly via Spack that may be related to this.  I can't remember exactly what the issues were, but this is on our to-do list to look into before the release.  Any advice would be appreciated.

**Comment by lindstro** [comment]
@hmaarrfk, @siebrenreker: The 1.0.0 release is now live.  Thanks for your patience.

**Comment by siebrenreker** [comment]
Thanks for the heads up @lindstro, we'll pick it up and begin testing it. Congratulations on getting to the 1.0.0!
Are you now planning to do [semantic versioning](https://semver.org/) going forward?

**Comment by lindstro** [comment]
Thanks, @siebrenreker.  Yes, we've entirely revamped our approach to versioning and will be using something very similar to semantic versioning going forward.

**Comment by hmaarrfk** [comment]
Is there some reason I can't find python easily? Has that cmake logic changed?

**Comment by lindstro** [comment]
@hmaarrfk Can you please be more specific?

**Comment by hmaarrfk** [comment]
Looking into it. It seems that i deleted one of my own patches that helped it find things with pypy.

I think I had asked about moving to a newer version of cmake that would be able to handle it but i might not have followed through with it.

Thanks all!

**Comment by hmaarrfk** [comment]
ill see if i can cleanup my patch enough to upstream

**Comment by hmaarrfk** [comment]
I think you use enough scikit-build stuff. I opened an issue: https://github.com/scikit-build/scikit-build/issues/736

**Comment by lindstro** [comment]
@hmaarrfk Thanks for all your help with this.  I noticed that the documentation for the conda [zfp](https://anaconda.org/conda-forge/zfp) and [zfpy](https://anaconda.org/conda-forge/zfpy) packages still points to version 0.5.5.  Also, the canonical URL for the zfp project is now https://zfp.llnl.gov.

I must confess to knowing nothing about conda(-forge).  Are you the maintainer of both packages?  Is https://github.com/conda-forge/zfp-feedstock dead?

**Comment by hmaarrfk** [comment]
See https://github.com/conda-forge/zfpy-feedstock/

Edits to the links would be appreciated 
https://github.com/conda-forge/zfpy-feedstock/blob/92f9eaa55887bf26c6b5c5d645952f4bd3ea50fc/recipe/meta.yaml#L87

**Comment by hmaarrfk** [comment]
We mostly renamed the main feedstock a while back.

**Comment by lindstro** [comment]
@hmaarrfk I forked the repo and updated the links, but I am not sure how to complete the checklist below.  All but the fork seem like conda specific things that I don't know how to handle.  How/where do I set the build number?  What does it mean to package the license file?

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

**Comment by hmaarrfk** [comment]
Package license file means that thsi line exists and doesn't fail:
https://github.com/conda-forge/zfpy-feedstock/blob/92f9eaa55887bf26c6b5c5d645952f4bd3ea50fc/recipe/meta.yaml#L90

It refers to the license of the source.

Build number refers to this line 
https://github.com/conda-forge/zfpy-feedstock/blob/92f9eaa55887bf26c6b5c5d645952f4bd3ea50fc/recipe/meta.yaml#L22

**Comment by hmaarrfk** [comment]
You can just edit the line you know how to edit.
