### ISSUE TITLE
cmocka_cloned configure error on Mac for latest master

### ISSUE THREAD

**Issue by JasonRuonanWang** [LLNL/zfp#150]
macOS 11.6.1
AppleClang 13.0.0.13000029
cmake 3.21.2

```
[ 21%] Performing build step for 'cmocka_cloned'
CMake Error: Invalid value used with --config
Usage: cmake --build <dir>             [options] [-- [native-options]]
       cmake --build --preset <preset> [options] [-- [native-options]]
Options:
  <dir>          = Project binary directory to be built.
  --preset <preset>, --preset=<preset>
                 = Specify a build preset.
  --list-presets
                 = List available build presets.
  --parallel [<jobs>], -j [<jobs>]
                 = Build in parallel using the given number of jobs. 
                   If <jobs> is omitted the native build tool's 
                   default number is used.
                   The CMAKE_BUILD_PARALLEL_LEVEL environment variable
                   specifies a default parallel level when this option
                   is not given.
  --target <tgt>..., -t <tgt>... 
                 = Build <tgt> instead of default targets.
  --config <cfg> = For multi-configuration tools, choose <cfg>.
  --clean-first  = Build target 'clean' first, then build.
                   (To clean only, use --target 'clean'.)
  --verbose, -v  = Enable verbose output - if supported - including
                   the build commands to be executed. 
  --             = Pass remaining options to the native tool.
make[2]: *** [tests/cmocka_cloned-prefix/src/cmocka_cloned-stamp/cmocka_cloned-build] Error 1
make[1]: *** [tests/CMakeFiles/cmocka_cloned.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

```

**Comment by lindstro** [comment]
The `master` branch does not make use of cmocka.  I assume you meant the default `develop` branch.

I can reproduce this issue with CMake 3.21.2 but not with an earlier version (3.13.4).  It appears that CMAKE_BUILD_TYPE is not propagated when the external cmocka project is being built (see [this line](https://github.com/LLNL/zfp/blob/b91dcafb4bf844565f82676f90c189ef68f9aa5c/tests/CMakeLists.txt#L20)).  This issue is further discussed [here](https://gitlab.kitware.com/cmake/cmake/-/issues/17645).  Let us look into how to best resolve the issue.

**Comment by JasonRuonanWang** [comment]
> The `master` branch does not make use of cmocka. I assume you meant the default `develop` branch.
> 
> I can reproduce this issue with CMake 3.21.2 but not with an earlier version (3.13.4). It appears that CMAKE_BUILD_TYPE is not propagated when the external cmocka project is being built (see [this line](https://github.com/LLNL/zfp/blob/b91dcafb4bf844565f82676f90c189ef68f9aa5c/tests/CMakeLists.txt#L20)). This issue is further discussed [here](https://gitlab.kitware.com/cmake/cmake/-/issues/17645). Let us look into how to best resolve the issue.

Yeah, the develop branch.

**Comment by lindstro** [comment]
We need to spend some time on this to get it right, as it seems to be a nontrivial issue to solve in a portable manner.  In the meantime, some possible workarounds include:

- Use an older version of CMake.
- Modify `src/CMakeLists.txt` to use `--config Release` or exclude the `--config` setting on macOS.
- Disable the tests via `-DBUILD_TESTING=OFF`.

**Comment by lindstro** [comment]
> * Modify `src/CMakeLists.txt` to use `--config Release` or exclude the `--config` setting on macOS.

Sorry, that should read `tests/CMakeLists.txt`.

**Comment by JasonRuonanWang** [comment]
@lindstro Thanks. I can live with -DBUILD_TESTING=OFF for now.

**Comment by tomandersen** [comment]
Thanks,

This worked for me on mac M1 with macOS 12.0.1

cd zfp
mkdir build
cd build
cmake -DBUILD_TESTING=OFF ..
cmake --build . --config Release
# ctest not gonna do anything

Well it built fine! I am hoping to put it to use soon. I needed 4D arrays.

**Comment by lindstro** [comment]
This issue has hopefully been resolved on `develop`.  Please let us know if the fix does not work for you.
