### ISSUE TITLE
Low-level compression

### ISSUE THREAD

**Issue by szellmann** [LLNL/zfp#151]
This is more a question than an issue, but I wasn't sure where else I should ask it. I'm using the low-level API to compress 3D fields. Thing is I cannot easily tell the exact dimensions of that field in advance (and thus also don't know how many blocks it'll give me, I determine that on the fly).

I pulled out a minimal sample out of my app, to illustrate the issue I'm running into / where I'm presumably misunderstanding how to use the API:
```
#include <stddef.h>                                                                          
#include <stdio.h>                                                                           
#include <stdlib.h>                                                                          
#include <string.h>                                                                          
#include <zfp.h>                                                                            
                                                                                             
typedef float Block[64];                                                                     
                                                                                             
size_t encode(float* out, Block* blocks, size_t numBlocks) {                                 
#if 0                                                                                        
    unsigned minbits = 0;                                                                        
#else                                                                                        
    unsigned minbits = 1024;                                                              
#endif                                                                       
    unsigned maxbits = minbits;                                                                
    unsigned maxprec = ZFP_MAX_PREC;                                                         
    int minexp = ZFP_MIN_EXP;         
                                                                          
    size_t bufsize = numBlocks*sizeof(Block); // enough scratch space                        
    void* buffer = malloc(bufsize);                                                          
    bitstream* stream = stream_open(buffer,bufsize);                                         
    zfp_stream* zfp = zfp_stream_open(stream);                                               
    zfp_stream_set_params(zfp,minbits,maxbits,maxprec,minexp);                               
    size_t bits = 0;                                                                         
    for (size_t i=0; i<numBlocks; ++i) {                                                     
        bits += zfp_encode_block_float_3(zfp,blocks[i]);                                     
    }                                                                                        
    size_t bytes = (bits+7)/8;                                                               
    memcpy(out,buffer,bytes);                                                                
    stream_flush(stream);                                                                    
    stream_close(stream);                                                                    
    zfp_stream_close(zfp);                                                                   
    free(buffer);                                                                            
    return bytes;                                                                            
}                                                                                            
                                                                                             
void decode(Block* blocks, size_t numBlocks, float* in) {                                    
    size_t bufsize = numBlocks*sizeof(Block); // enough scratch space                        
    void* buffer = malloc(bufsize);                                                          
    bitstream *stream = stream_open((void*)in,bufsize);                                      
    zfp_stream *zfp = zfp_stream_open(stream);                                               
    size_t bits = 0;                                                                         
    for (size_t i=0; i<numBlocks; ++i) {                                                     
        zfp_decode_block_float_3(zfp,blocks[i]);                                             
    }                                                                                        
    stream_flush(stream);                                                                    
    stream_close(stream);                                                                    
    zfp_stream_close(zfp);  
    free(buffer);   
}

int main(int argc, char** argv) {                                                         
    Block raw[2];                                                                         
    for (int i=0; i<64; ++i) {                                                            
        raw[0][i] = (float)i;                                                             
        raw[1][i] = (float)i*2;                                                           
    }                                                                                     
    float* buf = malloc(2*sizeof(Block));                                                   
    size_t s = encode(buf,raw,2);                                                         
    Block zfp[2];                                                                         
    decode(zfp,2,buf);                                                                    
    for (int i=0; i<64; ++i) { printf("%f\n",zfp[0][i]); }                                
    for (int i=0; i<64; ++i) { printf("%f\n",zfp[1][i]); }                                
} 
```

So in `main` I'm just encoding and then decoding two blocks, and the `#if 0` allows me to switch between fixed-rate and variable-rate compression.

I'd expect the program to print two sequences of non-zero floats. And it actually does with variable-rate compression. When I switch to fixed-rate, however, I find that the 1st block prints as desired, while the 2nd block gets decompressed into all zeros.

I wonder if I'm missing something obvious which causes the two different behaviors. Note that with variable rate I'm able to properly encode and then decode a large, 2.5GB data set (but I'll eventually need random access and thus fixed-rate compression).

Any tips what I might be doing wrong are very much appreciated, and sorry for asking such a general question here on the issue tracker.

**Comment by lindstro** [comment]
I see a few issues here:

First, you should not compute `bytes = (bits+7)/8` before calling `stream_flush()`, because you also need to copy any bits buffered by zfp in whole words (not just whole bytes).  Instead, use `bits += stream_flush(stream);` before counting the number of bytes written.

Second, you have not set the compression parameters in `decode()` via `zfp_stream_set_params()`.  They need to be the exact same parameters used in `encode()`.  zfp can help you here if you're willing to write and then read a [header](https://zfp.readthedocs.io/en/release0.5.5/high-level-api.html#c.zfp_write_header), which will ensure that encoder and decoder use the same compression parameters.

Third, in variable-rate mode, you should not set `maxbits = 0`.  Instead, use `maxbits = ZFP_MAX_BITS`.  And it's possible (albeit unlikely) that the size of the compressed output exceeds the size of the input, so call `zfp_stream_maximum_size()` after setting the compression parameters to give you a conservative estimate of how much memory is needed for the compressed stream.

Some other minor issues: `float* out` is not an appropriate type for the compressed data, which is a raw set of bits (not floats).  I would suggest `void*` instead.  Also, `buffer` is allocated in `decode()` but not used.

**Comment by szellmann** [comment]
Awesome, that helped me! Thank you!

In retrospect, I'm a bit embarrassed because the issue with setting the compression parameters in `decode()` as well is kinda obvious - whereas adding the output of `stream_flush()` wasn't and that would definitely have gone unnoticed by me. In regards to setting compression parameters, I guess where I was coming from is that image formats such as JPEG or PNG would carry that information along, and libjpeg or libpng only require you to set that on `encode()`. But yeah, totally obvious, especially with the fixed-rate format that, iiuc, only stores per-block information.

In regards to the minor issues, those are just leftovers from porting my application and accidentally snuck into the sample (although I later also debated if what I was seeing was an alignment issue related to using `float*` here).

Closing this issue, and again thanks a lot!

**Comment by lindstro** [comment]
Having to specify the compression parameters during decompression is indeed unusual, but because zfp supports compressing very small blocks individually--especially via the low-level interface--it is a necessity.  By supporting headers as an optional feature, you can always embed such information when you need it.  The need to flush streams is not uncommon, but it's easy enough to forget to count those bits.  Glad things are working now.
