### ISSUE TITLE
ZFP test fails with HIP

### ISSUE THREAD

**Issue by data-panda** [LLNL/zfp#159]
Tried building `zfp/feature-hip-support` following the instructions in #142. With a bit of changes system specific changes here and there (for eg. letting the build find the right hipCUB etc CMake file for Rocm 5.0), I was able to get a successful build on a system with AMD MI100 GPUS. 

Test: `testHip` - Success
```
[==========] Running 2 test(s).
[ RUN      ] given_withHip_when_4dCompressHipPolicy_expect_noop
[       OK ] given_withHip_when_4dCompressHipPolicy_expect_noop
[ RUN      ] given_withHip_when_4dDecompressHipPolicy_expect_noop
[       OK ] given_withHip_when_4dDecompressHipPolicy_expect_noop
[==========] 2 test(s) run.
[  PASSED  ] 2 test(s).
```

Test: `testZfpHip3dFloat` - Fail
```
[==========] Running 13 test(s).
[ RUN      ] when_seededRandomSmoothDataGenerated_expect_ChecksumMatches
[       OK ] when_seededRandomSmoothDataGenerated_expect_ChecksumMatches
[ RUN      ] given_Hip_3dFloatArray_when_ZfpCompressDecompressFixedRate_expect_BitstreamAndArrayChecksumsMatch
                                Fixed rate param: 8
                                        Compress time (s): 0.210157
                                        Decompress time (s): 0.010475
                                Fixed rate param: 16
                                        Compress time (s): 0.002225
                                        Decompress time (s): 0.002265
                                Fixed rate param: 32
                                        Compress time (s): 0.001949
                                        Decompress time (s): 0.002587
[       OK ] given_Hip_3dFloatArray_when_ZfpCompressDecompressFixedRate_expect_BitstreamAndArrayChecksumsMatch
[ RUN      ] given_Hip_3dFloatArray_when_ZfpCompressFixedPrecision_expect_BitstreamAndArrayChecksumsMatch
                                Fixed precision param: 8
                                        Compress time (s): 0.013345
                                Fixed precision param: 16
                                        Compress time (s): 0.001646
                                Fixed precision param: 32
                                        Compress time (s): 0.001827
[       OK ] given_Hip_3dFloatArray_when_ZfpCompressFixedPrecision_expect_BitstreamAndArrayChecksumsMatch
[ RUN      ] given_Hip_3dFloatArray_when_ZfpCompressFixedAccuracy_expect_BitstreamAndArrayChecksumsMatch
                                Fixed accuracy param: 0.500000
                                        Compress time (s): 0.001732
                                Fixed accuracy param: 0.250000
                                        Compress time (s): 0.001559
                                Fixed accuracy param: 0.062500
                                        Compress time (s): 0.001659
[       OK ] given_Hip_3dFloatArray_when_ZfpCompressFixedAccuracy_expect_BitstreamAndArrayChecksumsMatch
[ RUN      ] given_Hip_3dFloatReversedArray_when_ZfpCompressDecompressFixedRate_expect_BitstreamAndArrayChecksumsMatch
                                Fixed rate param: 8
"Memobj map does not have ptr"
Aborted (core dumped)
```

I also modified the `simple.c` to compress and decompress with fixed rate bits per value of 8 (Compression Ratio 4 for float). While running he compression with execution policy: `zfp_exec_hip`, I get the following error:
```
"Invalid DeviceId less than 0"
Aborted (core dumped)
```

I believe from the output of `testZfpHip3dFloat` and it's other counterparts that (de)compression is happening fine and the error that I see w.r.t segfault is different that what I see in the case of modified `simple.c` for Hip execution policy. 

Overall on the snapshot of zfp I am using (https://github.com/LLNL/zfp/commit/03ad1ee6c2b9de20f1af97705edc83dbab5fa296) `testexec` reports the following summary:
```
299 of 1728 tests failed
  all 864 serial tests passed
  299 of 864 HIP tests failed
```

Any ideas why the tests could be failing? I will anyway see in the source code of the tests to dig a bit deep!

**Comment by lindstro** [comment]
There are some known issues with the variable-rate modes that may cause some testexec tests to fail, but I'm not aware of fixed-rate mode failing.  However, I believe we have not yet tested zfp with ROCM 5.0.  I'd like to try to reproduce this issue.  Can you please let us know what changes you made for ROCM 5.0 and include your modified simple.c?

PS. I'm on vacation this week and will not have much time to work on this until next week.

**Comment by lindstro** [comment]
@data-panda Can you please share your relevant changes so we can attempt to reproduce and debug this issue?

Some of the ROCM 5.0 build issues are likely to be addressed on PR #161, but we're not quite yet ready to merge it.

**Comment by data-panda** [comment]
@lindstro After a bit of tinkering around I reached a state where I am seeing all "fixed rate" tests passing even the HIP ones. So I am trying to see and include some changes from the unit test: `testexec` into my changed `simple.c`. Unfortunately the system with MI100 is being taken down for a scheduled maintenance activity today. I will post the outcomes and irrespective of success and failure will also share the modified `simple.c` by this week end!

**Comment by lindstro** [comment]
@data-panda Would be great if you could share your changes and results so we can start looking into this issue on our end.

**Comment by data-panda** [comment]
closing this for now as we are working in AMD dev team to address this. Will post the update and re-open if needed!
