### ISSUE TITLE
ZFP and H5Z-ZFP: Changed ZFP_VERSION_RELEASE value

### ISSUE THREAD

**Issue by jwsblokland** [LLNL/zfp#160]
Hello all,

The other day, I noticed the commit of 29 March has changed the file "version.h". One of changes is that the define `ZFP_VERSION_RELEASE` is different now. In the past it was defined as

`#define ZFP_VERSION_RELEASE ZFP_VERSION_PATCH`

and now it is

`#define ZFP_VERSION_RELEASE ZFP_VERSION_MAJOR`

This change gives a problem when I try to build the HDF5 plugin H5Z-ZFP. In this plugin the ZFP version is determined from the variables ZFP_VERSION_MAJOR, ZFP_VERSION_MINOR and ZFP_VERSION_RELEASE (see H5Zzfp.c). Therefore in the past the version used to be `0.5.5` while now it has become `0.5.0`. Could you @lindstro, @markcmiller86 and @GarrettDMorrison please advice what the best way forward is? It is straightforward to change H5Zzfp.c but first I want to make sure this is the right thing to do.

Best regards,
   Jan-Willem

**Comment by lindstro** [comment]
I believe this change to `ZFP_VERSION_RELEASE` is a mistake. @GarrettDMorrison can you please comment?  Going forward, I think H5Z-ZFP ought to use `ZFP_VERSION_PATCH` as `ZFP_VERSION_RELEASE` exists only for backwards compatibility.

**Comment by GarrettDMorrison** [comment]
Yes that was not an intended change and I'm unsure how it snuck in there as no changes to that line were needed for this commit. I have reverted this change. Having said that I agree with @lindstro that going forward it would be better to use ZFP_VERSION_PATCH.

**Comment by jwsblokland** [comment]
Thanks all for the explanation and for reverting the unintended change of ZFP_VERSION_RELEASE. Together with @markcmiller86 I will update H5Z-ZFP such it will make use of ZFP_VERSION_PATCH instead of ZFP_VERSION_RELEASE.
