### ISSUE TITLE
missing link file

### ISSUE THREAD

**Issue by qingyiyi** [LLNL/zfp#173]
Excuse me, I installed it under the ubuntu system according to the documentation, but there are only .so files and no .a files in my lib folder, which shows that all my functions are undefined, what is the problem

**Comment by GarrettDMorrison** [comment]
By default zfp will build with shared libraries enabled on CMake. If this is with CMake (I'm assuming it is since you mentioned installing) then you will want to set -DBUILD_SHARED_LIBS=OFF to ensure a static library is generated.

**Comment by qingyiyi** [comment]
thank you very much！
