### ISSUE TITLE
Support MacOS Universal2 or arm64 Wheels

### ISSUE THREAD

**Issue by william-silversmith** [LLNL/zfp#175]
Hi Dr. Lindstrom,

I have recently started using zfp (as a part of a vector field compression package I wrote [zfpc](https://github.com/seung-lab/zfpc)) and some of my users on Apple Silicon are asking if zfpy universal2 wheels could be made available. There is a workaround to get x86 binaries working on that platform, but less sophisticated users may not know how to do it.

The M1 and M2 platforms uses an arm64 architecture for the chip, but includes a program called rosetta2 which translates x86_64 binaries into arm64 (almost) invisibly when used correctly. Python decided to accommodate x86 and arm64 macs together by creating "fat" universal2 wheels that include both x86 and arm64 binaries in the same wheel. Python then selects the appropriate architecture at runtime.

My cmake knowledge is a little lacking, but I was able to figure out how to compile `libzfp.a` with both architectures and create universal2 wheels. With a little guidance, I could submit a PR with the below script integrated into cmake.

```sh
#!/usr/bin/sh

ARMDIR=build_macos/arm64
X86DIR=build_macos/x86_64

mkdir -p $ARMDIR
mkdir -p $X86DIR

cmake -B $ARMDIR -S . -DCMAKE_OSX_ARCHITECTURES=arm64 -DBUILD_TESTING=NO -DBUILD_SHARED_LIBS=OFF
cmake -B $X86DIR -S . -DCMAKE_OSX_ARCHITECTURES=x86_64 -DBUILD_TESTING=NO -DBUILD_SHARED_LIBS=OFF

DIR=$(pwd)
cd $DIR/$ARMDIR && make
cd $DIR/$X86DIR && make

# generates "fat" ./libzfp.a
lipo -create -output $DIR/libzfp.a $DIR/$ARMDIR/lib/libzfp.a $DIR/$X86DIR/lib/libzfp.a

# generates universal2 (with some small changes to setup.py to find the library)
# only py38, py39, py310 support universal2
python setup.py bdist_wheel 
```

On an Apple Silicon Mac, you can use the command `lipo -archs libzfp.a` to list which architectures the static library supports.

**Comment by william-silversmith** [comment]
There's another step or two needed to get the wheel to compile right that I need to figure out. Getting: 

```ImportError: dlopen(/Users/wms/.virtualenvs/tmp/lib/python3.9/site-packages/zfpy.cpython-39-darwin.so, 0x0002): symbol not found in flat namespace '_stream_close'```

In C++, this can be fixed by adding `-stdlib=libc++`, will need to do some research for C.

A working C compilation of another library can be seen here: https://github.com/seung-lab/pyspng-seunglab/blob/bfe9e53d3519e15ed9a0dbd4913a5e89df9d177f/vendor/Makefile

**Comment by william-silversmith** [comment]
Seem to have gotten it working with the following setup.py:

```python
from setuptools import setup, Extension
import numpy as np

setup(
    name="zfpy",
    version="1.0.0",
    author="Peter Lindstrom",
    author_email="zfp@llnl.gov",
    url="https://zfp.llnl.gov",
    description="zfp compression in Python",
    long_description="zfp is a compressed format for representing multidimensional floating-point and integer arrays. zfp provides compressed-array classes that support high throughput read and write random access to individual array elements. zfp also supports serial and parallel compression of whole arrays using both lossless and lossy compression with error tolerances. zfp is primarily written in C and C++ but also includes Python and Fortran bindings.",
    ext_modules=[Extension("zfpy", ["python/zfpy.pyx"],
                           include_dirs=["include", np.get_include()],
                           libraries=["zfp"])]
)
```

**Comment by lindstro** [comment]
@william-silversmith Thanks for this contribution.  Let us look it over.

@da-wad Can you please provide some input?

**Comment by da-wad** [comment]
Hi - thanks for bringing this to my attention @lindstro 

Our build system for Python wheels uses cibuildwheel, which has [introduced arm64 support](https://cibuildwheel.readthedocs.io/en/stable/options/#build-skip). So since there is demand for this we should be building it for you and distributing via PyPI, rather than expecting everyone to build it themselves.

If we can provide both `x86_64` and `arm64` tagged wheels with the [commit I just pushed to zfpy-wheels](https://github.com/LLNL/zfpy-wheels/commit/7bd4a981933c38fdafd96414735963ef496c009e) and pip can pick the right one then I'd rather avoid making "fat" wheels. [Ignore the later commit - can't find out how to skip uploading wheels which have already been built rather than erroring...]

Please let us know whether the new `arm64` tagged wheels [now on PyPI](https://pypi.org/project/zfpy/1.0.0/#files) do what you need them to?

**Comment by william-silversmith** [comment]
Hi, thanks so much, I didn't know that cibuildwheel finally has arm64 support. 

I opened an arm64 terminal and tried installing zfpy but it seems to have some kind of linking problem.

```
(zfpyarm) wms:~$ pip install zfpy
Collecting zfpy
  Downloading zfpy-1.0.0-cp39-cp39-macosx_11_0_arm64.whl (89 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.3/89.3 kB 1.1 MB/s eta 0:00:00
Installing collected packages: zfpy
Successfully installed zfpy-1.0.0
(zfpyarm) wms:~$ python
[notice] A new release of pip available: 22.1.2 -> 22.2.2
[notice] To update, run: pip install --upgrade pip
Python 3.9.13 (v3.9.13:6de2ca5339, May 17 2022, 11:37:23) 
[Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import zfpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/Users/wms/.virtualenvs/zfpyarm/lib/python3.9/site-packages/zfpy.cpython-39-darwin.so, 0x0002): symbol not found in flat namespace '_stream_close'
>>> ^D
(zfpyarm) wms:~$ arch
arm64
```

**Comment by william-silversmith** [comment]
The shared object file in my virtualenv does look like it does have contents:

```
-rwxr-xr-x   1 wms  staff   240K Aug 15 14:34 zfpy.cpython-39-darwin.so
```
```
(zfpyarm) wms:~/.virtualenvs/zfpyarm/lib/python3.9/site-packages$ lipo -detailed_info zfpy.cpython-39-darwin.so
input file zfpy.cpython-39-darwin.so is not a fat file
Non-fat file: zfpy.cpython-39-darwin.so is architecture: arm64
```

**Comment by william-silversmith** [comment]
Here's an archive of working statically compiled libzfp.a for each type (you'll have to rename them, they're named libzfp_fat.a, libzfp_x86.a, and libzfp_arm64.a). Maybe it'll be helpful for debugging.
[Archive.zip](https://github.com/LLNL/zfp/files/9339202/Archive.zip)

**Comment by da-wad** [comment]
I see... not really familiar with building for mac myself, and don't have one to test on... But the difference I see between your calls to cmake and those in zfpy-wheels is the `-DBUILD_SHARED_LIBS=OFF` flag.

I've added this flag [for the mac wheels build](https://github.com/LLNL/zfpy-wheels/commit/31bbeeffe75f8787fd291c3e65bdc5ebfeac80bb) and created a post-release [which is in PyPI here](https://pypi.org/project/zfpy/1.0.0.post1/#files).

They seem suspiciously small, but do these work for you, @william-silversmith ?

**Comment by william-silversmith** [comment]
Hi David, thanks again for your help! 

Your suspicion was correct, they are too small and an attempted installation had the same issue.

The `-DBUILD_SHARED_LIBS=OFF` makes the compiler issue static `libzfp.a` instead of a shared library. If the shared library isn't also packaged, the binary won't work. I think it'd be worth trying adding that flag unless we want to require people to build or install zfp on their system beforehand.

**Comment by lindstro** [comment]
This shared vs. static library issue on macOS is one we've run into in the past, and @halehawk has worked toward resolving it; see #107, which appeared to work for you in the past, @william-silversmith.  I don't know the details of the issue or how it's resolved, but we need to be able to build macOS wheels that do not require an independent zfp installation.

@halehawk Can you please weigh in?

**Comment by william-silversmith** [comment]
I'm a bit of an easier customer than some of my users. I have a rosetta2 terminal [set up](https://www.byran.tech/html/how-to-make-a-rosetta-2-emulated-x86-terminal-on-arm-apple-silicon-chips.html) so I can consume x86 binaries without a problem on Apple Silicon. rosetta2 will translate an x86 binary into arm64 invisibly. Valid x86 binaries on PyPI solved my issue in #107.

People that use the native terminal and are naive to the underlying architecture require arm64 binaries or fat universal2 binaries that include x86 and arm64 instructions.

Thanks so much for investigating!

**Comment by william-silversmith** [comment]
I suspect that something screwy is going on with the additional "repair wheel" step at the end. Maybe try switching that off and see what happens? With a static library build, no need to "delocate" a dynamic library.

**Comment by halehawk** [comment]
Sure, I will install it on my mac m1 to see if there is any problem.

**Comment by halehawk** [comment]
I see William's error on my mac m1 laptop.

**Comment by halehawk** [comment]
@da-wad @lindstro @william-silversmith I ran the latest zfpy-wheels repo and looked at the log file from git action, I saw the cmake errors, then the build wheel used the existing files which should be files for python 3.7. Did you see the same thing? I saw the same errors w/o SHARED_LIBS.

Running before_build...
  
  + pip install numpy cython scikit-build cmake; PYTHON_INCLUDE=$(python -c 'from sysconfig import get_paths; print(get_paths()["include"])'); PYTHON_LIB=$(python -c 'import sysconfig; print(sysconfig.get_config_var("LIBDIR"))'); mkdir build; cd build; cmake .. -DBUILD_ZFPY=ON -DBUILD_TESTING=OFF -DPYTHON_LIBRARY=$PYTHON_LIB -DPYTHON_INCLUDE_DIR=$PYTHON_INCLUDE -DBUILD_SHARED_LIBS=OFF; make; cd ..; mkdir build/lib/Release; cp -RP build/lib/libzfp.*  build/lib/Release; ls build/lib;
  Collecting numpy
    Downloading numpy-1.23.2-cp38-cp38-macosx_10_9_x86_64.whl (18.1 MB)
       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.1/18.1 MB 39.9 MB/s eta 0:00:00
  Collecting cython
    Using cached Cython-0.29.32-py2.py3-none-any.whl (986 kB)
  Collecting scikit-build
    Using cached scikit_build-0.15.0-py2.py3-none-any.whl (77 kB)
  Collecting cmake
    Using cached cmake-3.24.0-py2.py3-none-macosx_10_10_universal2.macosx_10_10_x86_64.macosx_11_0_arm64.macosx_11_0_universal2.whl (77.9 MB)
  Collecting distro
    Using cached distro-1.7.0-py3-none-any.whl (20 kB)
  Requirement already satisfied: wheel>=0.29.0 in /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/cibw-run-5etqjafo/cp38-macosx_x86_64/build/venv/lib/python3.8/site-packages (from scikit-build) (0.37.1)
  Requirement already satisfied: setuptools>=28.0.0 in /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/cibw-run-5etqjafo/cp38-macosx_x86_64/build/venv/lib/python3.8/site-packages (from scikit-build) (63.4.2)
  Collecting packaging
    Using cached packaging-21.3-py3-none-any.whl (40 kB)
  Collecting pyparsing!=3.0.5,>=2.0.2
    Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
  Installing collected packages: cmake, pyparsing, numpy, distro, cython, packaging, scikit-build
  Successfully installed cmake-3.24.0 cython-0.29.32 distro-1.7.0 numpy-1.23.2 packaging-21.3 pyparsing-3.0.9 scikit-build-0.15.0
  mkdir: build: File exists
  -- Compiling with C standard: 99
  -- Compiling with C++ standard: 98
  -- Found PythonLibs: /Library/Frameworks/Python.framework/Versions/3.8/lib (found version "3.8.10") 
  -- Found PythonInterp: /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/cibw-run-5etqjafo/cp37-macosx_x86_64/build/venv/bin/python3.7  
CMake Error at python/scikit-build-cmake/FindPythonExtensions.cmake:303 (list):
    list GET given empty list
  Call Stack (most recent call first):
    python/CMakeLists.txt:3 (include)
  
  
  CMake Error at python/scikit-build-cmake/FindPythonExtensions.cmake:307 (list):
    list GET given empty list
  Call Stack (most recent call first):
    python/CMakeLists.txt:3 (include)
  
  
  CMake Error at python/scikit-build-cmake/FindPythonExtensions.cmake:311 (list):
    list GET given empty list
  Call Stack (most recent call first):
    python/CMakeLists.txt:3 (include)
  
  
  CMake Error at python/scikit-build-cmake/FindPythonExtensions.cmake:315 (list):
    list GET given empty list
  Call Stack (most recent call first):
    python/CMakeLists.txt:3 (include)




  See also "/Users/runner/work/zfpy-wheels-halehawk-1.0.0/zfpy-wheels-halehawk-1.0.0/build/CMakeFiles/CMakeOutput.log".
  See also "/Users/runner/work/zfpy-wheels-halehawk-1.0.0/zfpy-wheels-halehawk-1.0.0/build/CMakeFiles/CMakeError.log".
  make: /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/cibw-run-ln7x6jr2/cp37-macosx_x86_64/build/venv/lib/python3.7/site-packages/cmake/data/CMake.app/Contents/bin/cmake: No such file or directory
  make: *** [cmake_check_build_system] Error 1
  mkdir: build/lib/Release: File exists
  Release
  libzfp.1.0.0.dylib
  libzfp.1.dylib
  libzfp.dylib

**Comment by halehawk** [comment]
So I don't think the problem is related with delocate, because the arm arch or x86 arch uses the same file directory to link to the libzfp.dylib.

**Comment by halehawk** [comment]
I figured it out. @da-wad @lindstro @william-silversmith, I confirmed that the delocate parts work. Please add "rm -rf build;" before "mkdir build;" in your .github/workflows/wheels.yml in the https://github.com/LLNL/zfpy-wheels. I don't want to create a PR in that repo any more, since the PR will be failed any way because it cannot pass the publish phase.

**Comment by halehawk** [comment]
Forgot to mention, please switch BUILD_SHARED_LIBS=ON

**Comment by lindstro** [comment]
@halehawk Thanks much for identifying and solving this issue.  Though the solution is surprising.  Should Actions not start from a clean directory?!

@da-wad Can you please incorporate and verify this solution?

**Comment by william-silversmith** [comment]
Building shared libs that are intended to be distributed in such a way that they must always be located next to the binary is a bit odd, seems like a good case for a static library, but hey if it works it works. 😎 

Thanks so much to you all for working on this. Looking forward to the arm64 binaries.

**Comment by da-wad** [comment]
If only it were that simple! I have done some more digging, and there appears to be a problem with delocate.

When you added the mac builds @halehawk [this line in wheels.yml](https://github.com/LLNL/zfpy-wheels/blob/9674f9a390e033b9340d104de75f257c33ea32b2/.github/workflows/wheels.yml#L66) prints the dependencies which will be dragged in to the repaired wheel.

And for the x64_86 mac wheels the output is what we'd hope for; this output corresponds to the libs which turn up in the PyPI wheels:
`/Users/runner/work/zfpy-wheels/zfpy-wheels/build/lib/Release/libzfp.1.0.0.dylib
 /usr/local/Cellar/libomp/14.0.6/lib/libomp.dylib`
  
But for the arm64 wheels this outputs... nothing! Any further thoughts?

**Comment by da-wad** [comment]
**Update**

Delocate has a `-v` flag which for x86_64 gives this output:
`INFO:delocate.delocating:Copying library /Users/runner/work/zfpy-wheels/zfpy-wheels/build/lib/libzfp.1.0.0.dylib to zfpy.dylibs/libzfp.1.0.0.dylib
  INFO:delocate.delocating:Copying library /usr/local/Cellar/libomp/14.0.6/lib/libomp.dylib to zfpy.dylibs/libomp.dylib
  INFO:delocate.delocating:Modifying install name in zfpy.dylibs/libzfp.1.0.0.dylib from /usr/local/opt/libomp/lib/libomp.dylib to @loader_path/libomp.dylib
  INFO:delocate.delocating:Modifying install name in zfpy.cpython-38-darwin.so from @rpath/libzfp.1.dylib to @loader_path/zfpy.dylibs/libzfp.1.0.0.dylib
  Fixing: /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/cibw-run-qxx0tbea/cp38-macosx_x86_64/built_wheel/zfpy-1.0.0.post3-cp38-cp38-macosx_10_9_x86_64.whl
  Copied to package .dylibs directory:
    /Users/runner/work/zfpy-wheels/zfpy-wheels/build/lib/libzfp.1.0.0.dylib
    /usr/local/Cellar/libomp/14.0.6/lib/libomp.dylib`
    
... and for arm64, just:
`Fixing: /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/cibw-run-qxx0tbea/cp38-macosx_arm64/built_wheel/zfpy-1.0.0.post3-cp38-cp38-macosx_11_0_arm64.whl`

I also ran `otool -l` on the zfpy.cpython-*-darwin.so files, getting identical output for the two architectures, So delocate _has_ to be doing something wrong.

**Comment by da-wad** [comment]
I've been doing some reading:
- [cibuildwheel docs](https://cibuildwheel.readthedocs.io/en/1.x/faq/#apple-silicon)
- [Github Actions blog](https://github.blog/changelog/2022-08-09-github-actions-self-hosted-runners-now-support-apple-m1-hardware/)

And from what I can see there, my best guess at this stage is that the delocation struggles as a consequence of the cross-compilation for arm64 on an intel runner. Github Actions appear to allow you to set up your own apple silicon to do this (since a couple of weeks ago) but does not appear to provide such runners themselves.

**Comment by halehawk** [comment]
Yes, the delocate not only fixed the lib path issue, it removed the path at
all.
Before deolcate:
build/bin/zfpy.cpython-39-darwin.so:
 @rpath/libzfp.1.dylib (compatibility version 1.0.0, current version 1.0.0)
 /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version
1311.0.0)
After delocate:
  zfpy.cpython-39-darwin.so:
  /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version
1311.0.0)

Also, I found out the cbuildwheel is installed for Python 3.10 and x64, but
I picked Python 3.9 and arm to build zfpy.
Run which python; uname -m; python -m pip install cibuildwheel
shell: /bin/bash -e {0}
env:
pythonLocation: /Users/runner/hostedtoolcache/Python/3.10.6/x64
/Users/runner/hostedtoolcache/Python/3.10.6/x64/bin/python
x86_64
Collecting cibuildwheel
Downloading cibuildwheel-2.9.0-py3-none-any.whl (63 kB)

Is there way to install cbuildwheel for ARM? If not, we cannot use git
action for macos build.

**Comment by william-silversmith** [comment]
Hi all, would you consider using the wheels I've compiled for arm64/i386 using a statically linked build? Some of my users are having issues with using software out-of-the-box on Apple Silicon in arm64 mode. My users have been successfully installing using these wheels manually.

You can find them here: https://github.com/seung-lab/cloud-volume/issues/561#issuecomment-1336280521

**Comment by da-wad** [comment]
Thanks for building and sharing those. I was able to upload them to PyPI: https://pypi.org/project/zfpy/1.0.0/#files

**Comment by da-wad** [comment]
Hi,

I would happily yank the .post1 and .post3 releases now we have some good wheels supporting arm64... however, this requires the 'Owner' role in PyPI and I only have 'Maintainer'. @lindstro - will you do this, or would you like to delegate?

Deleting the individual broken arm64 wheels is also something we should do, but I'm not sure about deleting the x86 mac wheels which I believe are working fine for x86 macs. I'm not sure why an M1 mac would try one of those ahead of a universal wheel?!

David

**Comment by william-silversmith** [comment]
The universal wheel is double the size (contains both binaries) so if an
individual wheel is available, pip will download the one that matches the
current architecture.

On M1, the native terminal will download the arm64 while if you enable
rosetta2 emulation it'll download x86_64.

Thank you so much for your help!

**Comment by da-wad** [comment]
Thanks @lindstro .post1 & .post3 are now yanked, and broken arm64 wheels deleted.

**Comment by william-silversmith** [comment]
This worked! Thank you all!
