### ISSUE TITLE
CFP API is not exposed via CMake configuration file

### ISSUE THREAD

**Issue by jwsblokland** [LLNL/zfp#176]
The other day, I have written several CMake tests for H5Z-ZFP. As you may know, one of the tests of H5Z-ZFP make use of cfp. What I noticed is that the cfp target is not exposed at all in the CMake configuration file which makes it not straightforward to use cfp. Furthermore, I wonder what is the best way of exposing cfp. I think it should like component of zfp. In this way someone can easily implement some logic for when cfp is available and for when it is not.

**Comment by GarrettDMorrison** [comment]
Thanks for making us aware of this. I agree that in the context of CMake it makes sense to treat cfp as a component of zfp. Have added some hooks for zfp into zfp-config.cmake (see its comments for details) that should properly expose the necessary targets. Let me know if this works for you.

**Comment by jwsblokland** [comment]
A moment ago, I have tested your implementation. It works smoothly with the H5Z-ZFP cfp test. Thanks for the quick fix.
