### ISSUE TITLE
CMake build installed executable missing library rpath

### ISSUE THREAD

**Issue by shaomeng** [LLNL/zfp#181]
When using cmake to build ZFP and then `make install`, the installed executable doesn't have the library path in its rpath field. This results in the installed executable unusable. 

It was observed in the follow environment:
OS: CentOS 7
Compiler: gcc-11.2.0
CMake: 3.18.2
ZFP: 1.0.0

**Comment by GarrettDMorrison** [comment]
@shaomeng Thanks for making us aware of the issue. I've pushed in a fix that I believe should address this. Let us know if you continue to experience problems.

**Comment by shaomeng** [comment]
Yeah, it works great now, thanks for fixing it!
