### ISSUE TITLE
libzfp.so.1:cannot open shared object file:No such file or directory

### ISSUE THREAD

**Issue by qingyiyi** [LLNL/zfp#185]
I installed zfp correctly, wrote a program, compiled and passed, but it shows that the zfplib.so.1 file cannot be found when running ,like the title, but this file does exist in my lib folder, what is the problem and how to solve it. please help me.

**Comment by GarrettDMorrison** [comment]
Does libzfp.so show up in your executable's rpath? If not you'll want to make sure that's done at compile or that it has access some other way (e.g. - through LD_LIBRARY_PATH). Let me know if libzfp is in the path and we can dig more into what's going on here.

**Comment by qingyiyi** [comment]
Thanks,I solved it by adding the path to zfplib.so.1 when compiling
