### ISSUE TITLE
64-bit compiler and OS requirement

### ISSUE THREAD

**Issue by MrSherish** [LLNL/zfp#194]
Reading through the [docs](https://zfp.readthedocs.io/en/release0.5.4/installation.html#build-targets), one can read:

```NOTE: zfp requires 64-bit compiler and operating system support.```

Does it also cover runtime or only compile-time? I would like to run the library under Android on 32-bit ARM builds and above is confusing for me.

**Comment by lindstro** [comment]
Really all that's needed is support for 64-bit signed and unsigned integer types by the compiler (even if done through emulation) that produces binaries that can be executed on the target platform.  I think OS support is a bit of a red herring as `libzfp` itself should not depend on it.  I don't know how 32-bit ARM handles 64-bit integer arithmetic.

**Comment by lindstro** [comment]
@MrSherish Just checking if zfp is working for you and whether we can close this issue.
