### ISSUE TITLE
Is safe to read values in parallel from a const_array with cache_size=0 ?

### ISSUE THREAD

**Issue by aavbsouza** [LLNL/zfp#198]
Hello everyone.
I was wondering if would be safe to read in parallel from a `const_array`? There is no classes like `private_const_view`  for `const_arrays`. However the  `const_array` classes  appears to have a similar structure with the `array` classes that needs to have a private cache to be read in parallel safely.

thanks

**Comment by aavbsouza** [comment]
I was mistaken, is possible to use the `private_const_view` with the `const_array` classes

**Comment by lindstro** [comment]
`const_array` classes do indeed support `private_const_view`, e.g.,
https://github.com/LLNL/zfp/blob/c4f175667568b70462de8d806a63773b3eb1fff7/include/zfp/constarray1.hpp#L42
This is the only way to access a `const_array` in a thread-safe manner.  Here's a simple example:
```
#include <iostream>
#include <omp.h>
#include "zfp/constarray1.hpp"

int main()
{
  // initialize 1D array to linear ramp
  const size_t n = 100;
  double field[n];
  for (size_t i = 0; i < n; i++)
    field[i] = i; 

  // initialize fixed-precision const_array, a
  zfp::const_array1d a(n, zfp_config_precision(10), field);

  // output const_array in parallel
  #pragma omp parallel
  {
    // obtain a thread-safe view, v, of a
    zfp::const_array1d::private_const_view v(&a);

    // determine loop bounds for this thread
    int thread = omp_get_thread_num();
    int threads = omp_get_num_threads();
    size_t min = (thread + 0) * n / threads;
    size_t max = (thread + 1) * n / threads;

    // loop over indices assigned to this thread
    for (size_t i = min; i < max; i++) {
      double val = v(i);
      // serialize output
      #pragma omp critical
      {
        std::cout << i << " " << val << std::endl;
      }
    }
  }

  return 0;
}
```

Specifying `cache_size=0` merely sets the cache size to its default of roughly &radic;*n* elements for an array with *n* elements and is unrelated to thread safety.

**Comment by aavbsouza** [comment]
Hello @lindstro thank you detailed reply.
