### ISSUE TITLE
Is psnr formula error in ZFP?

### ISSUE THREAD

**Issue by BingluCS** [LLNL/zfp#207]
In the function "print_error" of the file "utils/zfp.c", the $psnr$ code is "psnr = 20 * log10((fmax - fmin) / (2 * erms))". 
The right formula seemly is the $10log_{10}((fmax-fmin)^2 \div mse)$. If the code use the $rmse$ to compute the $psnr$, the right code should be  "psnr = 20 * log10((fmax - fmin) / (erms))". The $rmse$ is simply equal to $\sqrt{mse}$.
This error has an impact on the comparison with other compressors.

**Comment by lindstro** [comment]
There are several definitions of PSNR in the literature.  Some use _f_<sub>max</sub> only, some use _f_<sub>max</sub> - _f_<sub>min</sub>, and some use (_f_<sub>max</sub> - _f_<sub>min</sub>) / 2.

zfp uses the convention that the peak signal is computed in a translation-invariant manner by first centering it on the mid-range (_f_<sub>min</sub> + _f_<sub>max</sub>) / 2, such that peak negative and positive values are the same (in magnitude).  The peak signal is then the maximum value, or amplitude, of this normalized signal.

For SNR, you replace peak signal with standard deviation as measure statistical dispersion, which is the _L_<sub>2</sub> norm of the signal after subtracting the mean (this centering on the mean minimizes the _L_<sub>2</sub> norm).  For PSNR, the _L_<sub>&infin;</sub> norm is used instead, and to minimize that you subtract the mid-range (_f_<sub>min</sub> + _f_<sub>max</sub>) / 2.  The resulting norm, i.e., peak signal, is (_f_<sub>max</sub> - _f_<sub>min</sub>) / 2.

**Comment by BingluCS** [comment]
Thanks for your answer. I found that the $psnr$ calculation formulas in sz and zfp are not consistent, the psnr calculated using the formula in sz will be $10log_{10}4$ higher than zfp.
