### ISSUE TITLE
Missing include to zfp.h in CUDA build

### ISSUE THREAD

**Issue by mohamed** [LLNL/zfp#21]
When building the CUDA port in 0.5.4, a compilation error is generated due to missing zfp.h.
See:

> -- Generating dependency file: /home/mbamakhr/repo/zfp/build/src/CMakeFiles/zfp.dir/cuda_zfp/zfp_generated_cuZFP.cu.o.NVCC-depend
/hpc/shared/eb_apps/rhel6/cuda/8.0.44-intel-2016a/bin/nvcc -M -D__CUDACC__ /home/mbamakhr/repo/zfp/src/cuda_zfp/cuZFP.cu -o /home/mbamakhr/repo/zfp/build/src/CMakeFiles/zfp.dir/cuda_zfp/zfp_generated_cuZFP.cu.o.NVCC-depend -ccbin /usr/bin/cc -m64 -Xcompiler ,\"-fPIC\",\"-O3\",\"-DNDEBUG\" -DNVCC -I/hpc/shared/eb_apps/rhel6/cuda/8.0.44-intel-2016a/include
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
In file included from /home/mbamakhr/repo/zfp/src/cuda_zfp/cuZFP.cu:3:
/home/mbamakhr/repo/zfp/src/cuda_zfp/cuZFP.h:4:17: error: zfp.h: No such file or directory
CMake Error at zfp_generated_cuZFP.cu.o.cmake:207 (message):
  Error generating
  /home/mbamakhr/repo/zfp/build/src/CMakeFiles/zfp.dir/cuda_zfp/./zfp_generated_cuZFP.cu.o
> make[2]: *** [src/CMakeFiles/zfp.dir/cuda_zfp/zfp_generated_cuZFP.cu.o] Error 1
> make[2]: Leaving directory `/home/mbamakhr/repo/zfp/build'
> make[1]: *** [src/CMakeFiles/zfp.dir/all] Error 2
> make[1]: Leaving directory `/home/mbamakhr/repo/zfp/build'
> make: *** [all] Error 2

I uploaded a pull request to fix this in: https://github.com/LLNL/zfp/pull/24

**Comment by mclarsen** [comment]
@mohamed Two questions: what host compiler are you using and what version of CMake are you using? I would like to reproduce on my end to better understand what the issue is. If you are using the intel compilers, that might explain the behavior and I can add that to my testing.

**Comment by mohamed** [comment]
@mclarsen Here are the tools versions:
- NVCC: release 8.0, V8.0.44
- GCC: 4.9.3
- CMake: 3.5.2

**Comment by mohamed** [comment]
@mclarsen I didn't notice that my pull request was messed up due to different branches. I cleaned things now and I have a new pull request #24  which should be merge-able onto develop
