### ISSUE TITLE
Cuda mode ZFP examples

### ISSUE THREAD

**Issue by AtilaSaraiva** [LLNL/zfp#212]
Hello folks, thank you for the amazing work,

I've been trying to wrap my head around how to use zfp with cuda. I couldn't find any example on the examples folder.

Is there a possibility for anyone to provide a few code snnipets or a full example?

All the best.

**Comment by lindstro** [comment]
We'll provide an example with the next release.  In the meantime, you can look at `tests/testexec.cpp` on the `staging` branch.  Really all you have to do is call [`zfp_stream_set_execution(stream, zfp_exec_cuda)`](https://zfp.readthedocs.io/en/release1.0.0/high-level-api.html#c.zfp_stream_set_execution) to enable CUDA execution before calling `zfp_compress()` or `zfp_decompress()`.  You also have to [build zfp](https://zfp.readthedocs.io/en/release1.0.0/execution.html#using-cuda) with CUDA support.

Note that CUDA support is a bit [limited](https://zfp.readthedocs.io/en/release1.0.0/execution.html#cuda-limitations-1); e.g., only fixed-rate mode is supported in zfp 1.0.0.  The next release will have support for other modes.

**Comment by AtilaSaraiva** [comment]
alright! thx, if you don't mind just another question: while using CUDA, when defining the field `zfp_field_2d(array, type, nx, ny * nz);` can array be a device array pointer?

**Comment by lindstro** [comment]
Yes, zfp detects where (un)compressed data resides and handles any necessary data movement.  See [documentation](https://zfp.readthedocs.io/en/release1.0.0/execution.html#device-memory-management).

**Comment by AtilaSaraiva** [comment]
Oh thx, for the help!
