### ISSUE TITLE
-h option not working for decompression

### ISSUE THREAD

**Issue by yunhua-deng** [LLNL/zfp#22]
`zfp -i datafile -z datafile.zfp <options>` works perfectly
`zfp -z datafile.zfp -o datafile.raw <options>` works perfectly
`zfp -i datafile -z datafile.zfp -o datafile.raw <options>` works perfectly

but, 
`zfp -i datafile -z datafile.zfp <options> -h` works
`zfp -z datafile.zfp -o datafile.raw -h` **doesn't work** and reports **array size must be nonzero**

What is the correct way to use _-h_ option in order to avoid typing _\<options\>_ in decompression?

PS: _datafile_ is around several MB in byte size

**Comment by lindstro** [comment]
I confirm that header support is broken in zfp 0.5.4.  In this version, we added a test to ensure that any user-specified array dimensions are nonzero for compression, which is incorrectly triggered when decompressing using a header.  We will push a fix in the next 24 hours.

**Comment by lindstro** [comment]
@yunhua-deng, I have pushed a fix on the develop branch.  Can you please verify that it addresses your issue?

**Comment by yunhua-deng** [comment]
After applying the fix, `zfp -i datafile -z datafile.zfp <options> -h & zfp -z datafile.zfp -o datafile.raw -h` works perfectly! Please feel free to close the issue once the fix is in the master.

**Comment by lindstro** [comment]
This fix has been added to zfp 0.5.5 and has been pushed to master.  I am closing the issue.
