### ISSUE TITLE
The data is wrong after decompression and decompression by zfp_field_1d, but it is correct when I use zfp_field_2d

### ISSUE THREAD

**Issue by Chuan1937** [LLNL/zfp#240]
Recently, I am working on a lossy compression tool for seismic data. My data is binary seismic data. It is about 1.6GB. When I use zfp_field_2d to compress and decompress the data, it is correct (because I put it into professional seismic processing software and compared it with the original data image), but the data obtained after decompressing and decompressing it with zfp_field_1d is wrong.

My data is one-dimensional. Initially, I converted it into a matrix to use zfp_field_2d, but I found that the time spent on matrix conversion alone is very long (but the compression time is very short). So I considered using zfp_field_1d, but his results were wrong.

I would appreciate it if you could assist me in reviewing my code to see if there are any issues. The file 'zfp_test_2d.txt' contains the correct output.

[zfp_test_1d.txt](https://github.com/user-attachments/files/16324899/zfp_test_1d.txt)
[zfp_test_2d.txt](https://github.com/user-attachments/files/16324902/zfp_test_2d.txt)

**Comment by Chuan1937** [comment]
I continued to test the decompressed data and found that the data values ​​were all 0。 I don't know how to solve it, I hope someone can give me some help

**Comment by lindstro** [comment]
You've included a lot of code, e.g., with support for multiple compression modes.  It would help us isolate the issue if you could reduce the 1D example to only the essential code being executed.

After taking a quick look, it appears that you're compressing `Samples * All_Trace` ~ 420 million floats at a rate of only 2 bits/value.  In 1D, this means each zfp block of 4<sup>1</sup> = 4 values gets assigned 2 * 4 = 8 bits/block.  This is not sufficient to even represent the empty-block bit and common exponent in the block, and no mantissa bits will be encoded, which is presumably why you're getting all-zeros.  You would have to increase the rate to at least 4 bits/value, though ideally more.  That said, zfp was not designed for 1D arrays, so quality will likely suffer.

In 2D, a rate of 2 bits/value will translate to 2 * 4<sup>2</sup> = 32 bits/block, which at least is sufficient to represent the leading mantissa bits.

If your data truly is 1D, then you might still benefit from compressing it as 2D.  From the 2D example, I assume you're compressing many small data sets, each of which is 2001 samples.  2001 is not divisible by zfp's 2D blocks of 4 * 4 = 16 values, but you could compress the first 2000 values as a nx = 4, ny = 500 2D data set and then store the last value uncompressed.  Or you could pad the last block with copies of that last value and then compress the resulting 2016 values as nx = 4, ny = 504.

**Comment by lindstro** [comment]
I believe this is not a problem with zfp per se and will go ahead and close the issue.
