### ISSUE TITLE
Installing "memory.h" conflicts with libc6

### ISSUE THREAD

**Issue by drdanz** [LLNL/zfp#25]
The line:

https://github.com/LLNL/zfp/blob/25a554e061a5323542f0e21fce2ee84e723ae774/CMakeLists.txt#L240

installs a `memory.h` file in `<prefix>/include`.
On debian, ubuntu and several other linux distributions, the `/usr/include/memory.h` is installed by `libc6-dev`.

This causes a conflict:
1) The libc version of the file is overwritten if the prefix is `/usr`
2) When searching for the libc version of`<memory.h>`, even for software that does not use zfp, the compiler is likely to find the zfp version before the right one, therefore the compilation is likely to fail.

I suggest to rename the file, or to put it in a subdirectory.

**Comment by drdanz** [comment]
CC @vvasco @barbalberto

**Comment by lindstro** [comment]
@drdanz, we are aware of these issues and are planning on a major revamp of the zfp directory structure for the next release, including CMake changes to isolate zfp headers from system headers.  Most if not all zfp headers will be placed under a zfp subdirectory.

We have a major release planned for March but may do another release before then to address this issue and others.

**Comment by lindstro** [comment]
@drdanz After closer inspection, `memory.h` is being installed in `<prefix>/include/zfp`, not in `<prefix>/include`.  So there ought not be a conflict.  I believe this holds for zfp 0.5.x, although I verified it only in the recent 0.5.5 release.  Can you please confirm?

`bitstream.h`, on the other hand, currently does get installed in `<prefix>/include`.  We will address this in the next release, even though we are not aware of any current conflicts.

**Comment by drdanz** [comment]
I think it was fixed by c4858c5ac2e73c6537ebe28b04776c23be68cb08, therefore it's fixed in 0.5.2.
Closing, this issue.
Thanks!
