### ISSUE TITLE
Link error for endtoend tests due to missing rt library

### ISSUE THREAD

**Issue by mohamed** [LLNL/zfp#26]
`endtoend` tests fail to link giving the following error:

```
[ 87%] Linking C executable ../../../bin/testZfpOmp3dInt64
/home/mbamakhr/repo/zfp/tests/src/endtoend/zfpEndtoendBase.c:469: error: undefined reference to 'clock_gettime'
/home/mbamakhr/repo/zfp/tests/src/endtoend/zfpEndtoendBase.c:487: error: undefined reference to 'clock_gettime'
/home/mbamakhr/repo/zfp/tests/src/endtoend/zfpEndtoendBase.c:469: error: undefined reference to 'clock_gettime'
/home/mbamakhr/repo/zfp/tests/src/endtoend/zfpEndtoendBase.c:487: error: undefined reference to 'clock_gettime'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/testZfpSerial2dFloat] Error 1
make[1]: *** [tests/src/endtoend/CMakeFiles/testZfpSerial2dFloat.dir/all] Error 2
```

Adding `rt` to `target_link_libraries` in the `zfp_add_test` function in `tests/src/endtoend/CMakeLists.txt` fixes the problem.

**Comment by mohamed** [comment]
@lindstro @mclarsen I uploaded a fix in #27. 
My setup is:
- RHEL 6
- GCC 4.9.3
- CUDA 8.0.44
- CMake 3.5.2

**Comment by mclarsen** [comment]
I have seen this before on another project. I don't think it has anything to do with CUDA, but i'll take a look when I have a chance. I am on travel this week, but working.

**Comment by mohamed** [comment]
@mclarsen You are right Matt. This has nothing to do with CUDA. It is in the endtoend tests which live only in the develop branch. It has to do with old glibc (see https://stackoverflow.com/questions/2418157/c-error-undefined-reference-to-clock-gettime-and-clock-settime). Older glibc require an explicit linking of 'rt' library.

**Comment by mohamed** [comment]
@salasoom I have verified the fix on Linux today. It works fine. I will close this issue.
