### ISSUE TITLE
Building static library with cmake?

### ISSUE THREAD

**Issue by mathomp4** [LLNL/zfp#28]
All, 

I'm trying to build H5Z-ZFP so first I need to build zfp (0.5.2, because it seems to be the latest supported version). However, when I did:

```
/ford1/share/gmao_SIteam/Baselibs/ESMA-Baselibs-5.2.0-ZFPTry/x86_64-unknown-linux-gnu/ifort_18.0.3.222-openmpi_3.1.0-gcc_6.3.0/Linux/bin/h5pcc H5Zzfp_plugin.o -shared -o plugin/libh5zzfp.so \
    -Wl,-rpath,/ford1/share/gmao_SIteam/Baselibs/ESMA-Baselibs-5.2.0-ZFPTry/x86_64-unknown-linux-gnu/ifort_18.0.3.222-openmpi_3.1.0-gcc_6.3.0/Linux/lib -Wl,-rpath,/ford1/share/gmao_SIteam/Baselibs/ESMA-Baselibs-5.2.0-ZFPTry/x86_64-unknown-linux-gnu/ifort_18.0.3.222-openmpi_3.1.0-gcc_6.3.0/Linux/zfp/lib \
    -L/ford1/share/gmao_SIteam/Baselibs/ESMA-Baselibs-5.2.0-ZFPTry/x86_64-unknown-linux-gnu/ifort_18.0.3.222-openmpi_3.1.0-gcc_6.3.0/Linux/zfp/lib -L/ford1/share/gmao_SIteam/Baselibs/ESMA-Baselibs-5.2.0-ZFPTry/x86_64-unknown-linux-gnu/ifort_18.0.3.222-openmpi_3.1.0-gcc_6.3.0/Linux/lib -lhdf5 -lzfp 
/usr/bin/ld: cannot find -lzfp
collect2: error: ld returned 1 exit status
```
So, no `libzfp.a`, and if I look at my zfp build:

```
(338)((no branch)) $ tree lib64/ bin/ 
lib64/
|-- libzfp.so -> libzfp.so.0
|-- libzfp.so.0 -> libzfp.so.0.5.2
`-- libzfp.so.0.5.2
bin/
|-- testzfp
`-- zfp

0 directories, 5 files
```
My `cmake` line was:
`cmake -DCMAKE_INSTALL_PREFIX=$(prefix)/zfp -DZFP_BIT_STREAM_WORD_SIZE=8 ..`

Is there an extra option I need to pass to CMake to generate the static library as well as the shared object library?

**Comment by mathomp4** [comment]
As a note, I'm eventually going to try and use `zfp` with netCDF files, so I'll probably be a frequent guest at  this and/or the H5Z-ZPF issues because I've never tried the netCDF filter interfaces. :)

**Comment by lindstro** [comment]
Try adding

    -DBUILD_SHARED_LIBS=OFF

to the cmake line.

To my knowledge, Unidata has not yet added zfp support, but I suppose this can be achieved via H5Z-ZFP.

**Comment by lindstro** [comment]
> Try adding
> 
> ```
> -DBUILD_SHARED_LIBS=OFF
> ```
> to the cmake line.
> 
> To my knowledge, Unidata has not yet added zfp support, but I suppose this can be achieved via H5Z-ZFP.

@mathomp4 Can you please let us know if this resolves your issue?  If so, then I'll go ahead and close it.

**Comment by mathomp4** [comment]
@lindstro Yes, that gave me the .a, though I could just never figure out how to get zfp in netCDF. I might try it again soon...

**Comment by lindstro** [comment]
Thanks for confirming.  Regarding zfp and netCDF, this is a question best directed to Mark Miller, the author of H5Z-ZFP.
