### ISSUE TITLE
endtoend test fail on Cygwin

### ISSUE THREAD

**Issue by mohamed** [LLNL/zfp#32]
endtoend tests fail on Cygwin because CMake no longer defines `WIN32` under Cygwin.
To fix this, we have two options:
1) Check if `__CYGWIN__` is defined
2) Use `__unix__` instead of `__linux__`. The Unix macro seems to be defined on Cygwin

I uploaded a fix on #31

**Comment by salasoom** [comment]
#31 is now merged. We used `__unix__` instead of `__linux__`
