### ISSUE TITLE
Would help to set version no in branches targetted for given release

### ISSUE THREAD

**Issue by markcmiller86** [LLNL/zfp#47]
Was using feature/lossless branch to enhance H5Z-ZFP.

I want H5Z-ZFP to conditionally compile against various versions of ZFP.

In this case, I wanted to do something like...

```
#if ZFP_VERSION_NO >= 0x0055
            case H5Z_ZFP_MODE_REVERSIBLE:
                zfp_stream_set_reversible(dummy_zstr);
                break;
#endif
```

But, building against ZFP's feature/lossless branch, my tests were all failing because that branch still has version number set at 0.5.4.

**Comment by lindstro** [comment]
I understand the motivation, but one problem with this is that any branch off the develop branch is just that--work in progress.  We don't necessarily know for sure in which release any given feature will end up.  I pointed you to this branch so you could see what the API will look like in preparation for the 0.5.5 release.  Your ifdef should work in a month or so.  As is our practice, we'll create a release barnch first for testing, which will have the correct version number.

**Comment by lindstro** [comment]
@markcmiller86 Can I close this issue or do you have any suggestions on how to handle this better?  As I previously said, it is difficult to bump the version number on feature branches until we know for sure in what release a particular feature will appear.  Any dependent software, like H5Z-ZFP, should probably not depend on a feature branch that has not yet been merged with a release branch.  But I'm open to suggestions.
