### ISSUE TITLE
bitstream.h is a very generic name

### ISSUE THREAD

**Issue by opoplawski** [LLNL/zfp#49]
Much like #25, "bitstream.h" is a very generic name and at the very least should be installed in under the include/zfp/.

**Comment by lindstro** [comment]
Agreed.  We're considering a complete re-organization of the directory structure to better address issues like this.

**Comment by GarrettDMorrison** [comment]
This has been fixed with the merge of refactor/install-directory into develop which moved Bitstream.h to include/zfp/. It just looks like we forgot to close this back then. I'm closing it now.
