### ISSUE TITLE
Array size must be nonzero

### ISSUE THREAD

**Issue by raffaele96** [LLNL/zfp#52]
Hi, zfp -i datafile not working, the message is "array size must be nonzero", the same if i try to decompress, may you help me?

**Comment by lindstro** [comment]
It sounds like you're not specifying the array dimensions using -1, -2, -3, or -4.  Can you please provide the complete command line you're using?

**Comment by raffaele96** [comment]
With this suggestion I tried zfp -i test.dat -d -1 2 -a 0.5 -s -o output.dat
But I'm not sure it works. The file test.dat is an array of 2 double elements saved in binary in c with fwrite.
I'm studying the topic recently, I'm still a bit confused. Thanks for your help

**Comment by lindstro** [comment]
This is correct usage assuming you want to compress only two double-precision values, which admittedly is not a realistic use case for any compressor.  Note that -o output.dat will write an uncompressed file that is the result of (lossy) compression followed by decompression.  Use -z if you wish to write the compressed data to file.

**Comment by raffaele96** [comment]
Thank you very much, now everything works!

**Comment by lindstro** [comment]
You're welcome.
