### ISSUE TITLE
Provide pip and/or conda installable Python package

### ISSUE THREAD

**Issue by impredicative** [LLNL/zfp#64]
It would really help to have a `pip` installable Python 3.7 compatible package published on https://pypi.org/ . This could then be updated whenever there is a new release of zfp. It will lower the barrier to using zfp. Thanks.

**Comment by lindstro** [comment]
Agreed, but unfortunately our Python developer has moved on to another project.  Any assistance with this would be appreciated.  In case it's helpful, I do have a pypi account.

**Comment by impredicative** [comment]
In that case, do you have a FTE opening for a Python developer?

**Comment by lindstro** [comment]
I'm afraid I don't have sufficient funding for an FTE, nor do I have enough work to keep a Python developer busy long term.

**Comment by jayvdb** [comment]
Dummies guide to packaging is to do `python setup.py test` , ensure that works, and then run PyPI `check-manifest` to ensure `MANIFEST.in` is complete, and then `python setup.py sdist` and use `twine` to upload it to PyPI.

Then get some python people to build it at home, fix any errors, etc, and then in the next release also do `python setup.py bdist_wheel` which is better for normal users.

**Comment by kmpaul** [comment]
@lindstro Would there be interest in making a conda package for zfp/zfpy instead of pip?  Pip is nice for pure python packages, but it's not the best for python packages with special C/C++ dependencies.

If this would be of interest, I think I can direct some effort to this tomorrow.

**Comment by kmpaul** [comment]
...Although, I agree that a wheel would be good, too.

**Comment by impredicative** [comment]
@kmpaul Speaking as a user, yes, conda works fine.

**Comment by lindstro** [comment]
@kmpaul Thanks for the offer!  Python is not my strength, and I'm not sure I'm qualified to answer your question.  Of course, any contributions that simplify life for our Python users are welcome.

I'm roping @GarrettDMorrison in on this, who is our resident Python expert.

**Comment by kmpaul** [comment]
I definitely think that a conda forge package for zfp would be loved by many.  So, since I'm in a hackathon for the next day (or two), I'll go ahead and start making some progress on this.  If the result is something you like, we can transfer ownership.

**Comment by kmpaul** [comment]
Of course!  And I'm happy to transfer ownership.  I understand that you all might be busy, though, so I happen to have some free cycles at the moment to do it.

**Comment by lindstro** [comment]
Awesome!  Thank you so much for your contributions, Kevin.

**Comment by kmpaul** [comment]
@lindstro You're more than welcome.  Thanks for the awesome `zfp` package!

Incidentally, who should I list as "conda recipe maintainers"?  I need github user IDs for everyone who will be (willing to be) a "maintainer" of this conda recipe.

**Comment by lindstro** [comment]
I hope you're willing to be one of them :-)  Please add me and @GarrettDMorrison.

**Comment by kmpaul** [comment]
Yes.  I'm the first person on the list.  :-)  And I'll stay there.  

I'll add you and Garrett.  Thanks!

**Comment by jayvdb** [comment]
Someone should register https://pypi.org/project/zfp/ , even if it is only an empty package, to reserve the name.  One of the first questions of distro packaging is "what name to use", and for Python to first answer is "the PyPI name".

**Comment by lindstro** [comment]
@jayvdb I'd be happy to do so through my PyPI account but could use some help.  I know there is documentation out there, but I cannot dedicate hours to figuring out how to set up an empty package at this time.  Is there an easy way to just register the package?

**Comment by impredicative** [comment]
@lindstro I have now registered [zfp](https://pypi.org/project/zfp/) on PyPI. I believe it is not necessary to do anything at all with this PyPI package right now, since @kmpaul is targeting an initial conda-forge package instead.

If I were to nevertheless transfer it, I suppose I would require an LLNL service account to grant ownership to, with @lindstro and @GarrettDMorrison added as maintainers. Any added PyPI account should ideally first enable 2FA for security.

**Comment by lindstro** [comment]
@impredicative Thanks for setting this up.  If you'd like to transfer the project, my PyPI account is lindstro.

**Comment by impredicative** [comment]
@lindstro Done. You now have Owner level access to it. From here you can adjust its permissions accordingly. Please however refer to the second paragraph of my prior post though for maximizing security and for organizing it to outlast any one person.

**Comment by lindstro** [comment]
@impredicative I demoted you to maintainer and will add @GarrettDMorrison as owner.  I also set up 2FA.

We could still use some help with setting up the pip package, in case anyone is willing to contribute.

**Comment by kmpaul** [comment]
I realized that I never posted that `zfpy` is now on conda-forge.  Has been for a little while.  In fact, if you look here (https://anaconda.org/conda-forge/zfpy) you can see that it already has >600 downloads.

Note that this package is meant to build `zfp` and install the `zfpy` Python bindings, so the package is named `zfpy`.

**Comment by jayvdb** [comment]
Please also reserve https://pypi.org/project/zfpy/ to avoid it being misused by someone else.

**Comment by impredicative** [comment]
> Please also reserve https://pypi.org/project/zfpy/ to avoid it being misused by someone else.

I will do this.

**Comment by impredicative** [comment]
> Please also reserve https://pypi.org/project/zfpy/ to avoid it being misused by someone else.

Done. @lindstro and @GarrettDMorrison are now its Owners.

**Comment by lindstro** [comment]
Thanks, @impredicative.

**Comment by lindstro** [comment]
Thanks to the efforts of @da-wad, we now have a `pip` installable package: https://pypi.org/project/zfpy/.  I'd like to thank @da-wad, @kmpaul, and everyone else who helped resolve this issue.
