### ISSUE TITLE
cfp_ or cfp. in docs

### ISSUE THREAD

**Issue by markcmiller86** [LLNL/zfp#69]
In the docs where [cfp interface](https://zfp.readthedocs.io/en/release0.5.5/arrays.html#c.cfp_array1f) is described, I think there are numerous instances of use of `cfp_arrayXx` that should really be `cfp.arrayXx` (e.g. dot and not underscore). I would have submitted PR but honestly wasn't absolutely sure either.

**Comment by salasoom** [comment]
You're correct on these. I've fixed them in this commit on `develop`
https://github.com/LLNL/zfp/commit/a7e77cc1feafdaf4189c21f5b18b1f49f9702c37
