### ISSUE TITLE
stream_word_bits declared outside extern "C"

### ISSUE THREAD

**Issue by markcmiller86** [LLNL/zfp#70]
in `include/bitstream.h`, shouldn't the declaration for `stream_word_bits` be put *inside* the extern "C" block?

```
/* forward declaration of opaque type */
typedef struct bitstream bitstream;

extern_ const size_t stream_word_bits; /* bit stream granularity */

#ifndef inline_
#ifdef __cplusplus
extern "C" {
#endif

```

**Comment by lindstro** [comment]
See `include/zfp/system.h`, where the `extern_` macro expands to `extern "C"` when a C++ compiler is used.  This macro is also used for Windows DLL storage-class attributes.

**Comment by markcmiller86** [comment]
Its still confusing. If `extern_` means `extern "C"`, why are both used within a few lines of each other?

**Comment by lindstro** [comment]
Depending on context, `extern_` expands to one of

- `extern`
- `extern __declspec(dllexport)`
- `extern __declspec(dllimport)`
- `extern "C"`
- `extern "C" __declspec(dllexport)`
- `extern "C" __declspec(dllimport)`

For reasons unknown to me, Microsoft requires the `__declspec` stuff for data but not for functions.  I'm also not sure if `extern "C" __declspace(dllexport) { <function declarations> }` is a valid construction, and `extern { <function declarations> }` is not valid C, so we do need two separate mechanisms for declaring data and functions.

Arguable a cleaner solution would be to define two different macros, e.g., `zfp_data_decl` and `zfp_func_decl`, to avoid `#ifdef __cplusplus` and `extern "C"` altogether.  We'd also need a `zfp_data_def` for data definitions to make MSVC happy.  Let me think about this.

I'd love to have someone explain to me what the benefits of dllimport/dllexport are.  Non-Microsoft compilers clearly do fine without them.
