### ISSUE TITLE
Feature request: Compute bound in error

### ISSUE THREAD

**Issue by NAThompson** [LLNL/zfp#73]
In [this](https://epubs.siam.org/doi/pdf/10.1137/18M1168832) paper, equation 5.1 and 5.2, the uniform norm error of the compression scheme is bound in terms of a constant K_b. Could this be computed in code, for example, if I parametrize zfp in some way, can I test those parameters against K_b before I do any compression?

**Comment by lindstro** [comment]
I'm not quite sure I understand the question and what you mean by parameterizing zfp.  Given that k, q, and d are fixed constants, K_b depends only on the user-specified number of bit planes, b, to keep, which in zfp translates to the parameter in [zfp_stream_set_precision.](https://zfp.readthedocs.io/en/release0.5.5/high-level-api.html#c.zfp_stream_set_precision).

Assuming x is represented in IEEE double precision, k = 53 and q = 62.  epsilon_k = 2^(1-k) and similarly for q.  d is the dimensionality of the multidimensional array represented by x.  So once you specify b (beta), K_b is known.

**Comment by lindstro** [comment]
Perhaps your question is whether K_b can be computed for you by a zfp function so that the user does not need to worry about the details of the formula 5.2.  That would indeed be a reasonable request.  We can add such a function.  Alternatively, we can compute beta given some desired "relative" error tolerance.

**Comment by NAThompson** [comment]
Yes, the second interpretation is correct. My apologies for lack of clarity.

**Comment by lindstro** [comment]
I will note that Eq 5.2 does not provide a point-wise relative error bound but rather bounds the max error relative to the max norm, M = |x|_infinity.  Let t = M K_b be the right-hand side of Eq 5.2.  Then you can ensure that the max error does not exceed t by calling [zfp_stream_set_accuracy](https://zfp.readthedocs.io/en/release0.5.5/high-level-api.html#c.zfp_stream_set_accuracy) with t as the tolerance.  Does that provide the functionality you need?

**Comment by NAThompson** [comment]
@lindstro : In fact I think that will work. Thanks!
