### ISSUE TITLE
GPU issue ?

### ISSUE THREAD

**Issue by cayrols** [LLNL/zfp#75]
Dear all,

I want to use zfp on GPU and for that, I am doing some bench.
I have uncommented the line #define CUDA_ZFP_RATE_PRINT 1 in shared.h file and did some runs.
The code is working well for 3D cubes of size of 100, 200, 300, 400 and 500.
However, we have noticed that for 3D cube of size 600, 700, or even 550 the run fails.

Let A be a 3D cude of size 600.
It turns out that the decompression of A, say A_d, seems to not working.
More precisely, the returned value of zfp_decompress is not 0, and the error ||A - A_d||_2 is of order 1e3. Note that in order to ease the computation of the error norm, we consider A and A_d as 1D vector.

Here is attached the test driver, the output obtained on a V100 GPU, and the needed additional compilation lines for a CMakeList.txt.
Please remove the .log extension from the source file, and add at the end of the examples/CMakeList.txt file the content of zfp_cmakelist_update.txt.

[zfp_cmakelist_update.txt](https://github.com/LLNL/zfp/files/3681693/zfp_cmakelist_update.txt)
[report_gpu_zfp_issue.c.log](https://github.com/LLNL/zfp/files/3681694/report_gpu_zfp_issue.c.log)
[zfp_exec_issue.log](https://github.com/LLNL/zfp/files/3681695/zfp_exec_issue.log)

It turns out that the decode rate of A is inf and the next call of zfp on GPU fails to allocate GPU memory.

Let me know if you need more details.
Sébastien

**Comment by lindstro** [comment]
Looking at the log file, I suspect that the combined output to stdout and stderr is appearing out of order, as "Unable to allocate d_Array on the GPU" should not appear before "GPU execution on data of size."  Maybe print all output to the same stream?

Anyway, if CUDA allocation of the data that is to be compressed failed, then I would not expect the subsequent call to `zfp_compress` to do anything reasonable, as it's being passed a bad pointer.  Is that what is happening?  There are multiple memory allocation calls on the order of 1.6 GB each.

Note that zfp automatically performs memory allocation and transfers if the data to be compressed resides on the host, so you shouldn't have to do this work manually.

**Comment by cayrols** [comment]
Thank you for your quick response.
I am sorry to not double check the log file.
When I compress and decompress a 3D block of size 10, it works.
Then, when I do the same for a 3D block of size 600, the compression seems to work, and then during the decompression, I got this 'inf' but with a returned value that is not 0.
Finally, when I recall the compression/decompression on the 3D block of size 10, I got the CUDA error during the allocation of the d_array, which means that something wrong happened during the decompression on the GPU.

About the automatic transfer, I want to plug zfp into a GPU code where the data already are on the GPU. So, if you can tell which routine I should use instead, that would be great.

**Comment by lindstro** [comment]
I see.  Let us look at this and see if we can reproduce the problem.  Does [CUDA-MEMCHECK](https://docs.nvidia.com/cuda/cuda-memcheck/index.html) report any issues?

If the data is already on the GPU, then what you're doing makes sense.

**Comment by cayrols** [comment]
I run cuda_memcheck and obtained 393 errors, shown in 
[cuda_memcheck_output.log](https://github.com/LLNL/zfp/files/3683937/cuda_memcheck_output.log)

**Comment by cayrols** [comment]
I run cuda_memcheck and obtained 393 errors, shown in 
[cuda_memcheck_output.log](https://github.com/LLNL/zfp/files/3691264/cuda_memcheck_output.log)

**Comment by lindstro** [comment]
@cayrols I ran your example, which succeeds for me:

GPU execution on data of size 10x10x10 => 8000
Error is 0.00e+00
GPU execution on data of size 600x600x600 => 1728000000
Error is 0.00e+00
GPU execution on data of size 10x10x10 => 8000
Error is 0.00e+00

The error is not being reported correctly as I had to comment out the BLAS code (I don't have BLAS installed on this machine).  Moreover, cuda-memcheck does not report any errors.

Since I cannot reproduce your problem, I am unsure how to proceed.

@mclarsen Do you have any suggestions on how to debug this issue?

**Comment by mclarsen** [comment]
I was unable to easily compile this program. I don't have a local machine to try this. I battled cmake on a GPU cluster and was not able to get it to link. Given that you were also unable to reproduce this, I am not sure if I should try to create a cmake project that will generically look for all the dependencies while making sure the compilers are consistent across the libs.

**Comment by lindstro** [comment]
@mclarsen I, too, had issues (due to BLAS dependencies) but gave you a tar ball on LC that should build.  Did you try that?

**Comment by mclarsen** [comment]
Ok. So I compile and ran it without issues.

My setup was a p100, cuda 10.1.168 and gcc 4.9.3 as the host compiler.

@cayrols Can you add some more details on how this was compiled?

**Comment by cayrols** [comment]
Thanks for your feedback.

Since then, I have tried on both Volta and Pascal GPUs. Both generating the same issue. I have tried to use gcc4.9.4 (4.9.3 is not installed on the machine).

So, I did as follow,
$ git clone https://github.com/LLNL/zfp.git zfp-exp
$ cd zfp-exp && mkdir build && cd build && cmake -DBUILD_EXAMPLES=ON -DZFP_WITH_CUDA=ON ..

then I compile the example and you already have the output.

Note that the output of module list is:
1) /cuda/10.1/gcc-7.3.0-l7ex              2) /cmake/3.10.3/gcc-7.3.0-q36g           3) /intel-mkl/2019.3.199/gcc-7.3.0-2pn4   4) /gcc/7.3.0/gcc-4.8.5-ox22

where cuda version is 10.1.105

Thanks

**Comment by cayrols** [comment]
Peter,

Thank you for your reply.
I have slightly modified the report_issue.c file in order to give the cube size as a parameter.

I have then run the following command:
for i in $(seq 1 12); do x=$((50 * i)); echo -n "$x : "; cuda-memcheck ./report_issue $x | grep errors; done

and got the following output on the V100 gpu :
50 : ========= ERROR SUMMARY: 0 errors
100 : ========= ERROR SUMMARY: 0 errors
150 : ========= ERROR SUMMARY: 0 errors
200 : ========= ERROR SUMMARY: 0 errors
250 : ========= ERROR SUMMARY: 0 errors
300 : ========= ERROR SUMMARY: 0 errors
350 : ========= ERROR SUMMARY: 0 errors
400 : ========= ERROR SUMMARY: 0 errors
450 : ========= ERROR SUMMARY: 0 errors
500 : ========= ERROR SUMMARY: 0 errors
550 : ========= ERROR SUMMARY: 296 errors
600 : ========= ERROR SUMMARY: 200 errors

I also have a way to check that the code works by computing the error after the decompression.
I have a larger test driver file if needed.

Also, quick question : which branch are you using for the test ? I might not be using the correct one.
[report_issue.c_v2.log](https://github.com/LLNL/zfp/files/3790781/report_issue.c_v2.log)

**Comment by lindstro** [comment]
Let me make sure I understand.  Are you saying that `cudaMalloc` succeeds but the code is generating tons of CUDA memory errors?  If `cudaMalloc` fails, then I would expect the code to terminate immediately with no further errors.

**Comment by cayrols** [comment]
I just did additional runs and found that the code does not work when the cube size is greater than 512.

 Using cuda_gdb, I got the following output:
(cuda-gdb) r 513                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
Starting program: /home/scayrols/workspace/zfp/build_full/bin/report_issue 513                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
[Thread debugging using libthread_db enabled]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
Using host libthread_db library "/lib64/libthread_db.so.1".                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
warning: File "/spack/opt/spack/linux-scientific7-x86_64/gcc-4.8.5/gcc-7.3.0-ox22fqdausgn5up7wb5d3mli5ngcbgri/lib64/libstdc++.so.6.0.24-gdb.py" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load".                                                                                                                                                                                                                                                                                                                                    
GPU execution on data of size 513x513x513 => 1080045576                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
[New Thread 0x7fff68098700 (LWP 36867)]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
[New Thread 0x7fff67897700 (LWP 36868)]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
Encode elapsed time: 0.01088 (s)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
\# encode3 rate: 92.43 (GB / sec)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
CUDA Exception: Warp Illegal Address                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
The exception was triggered at PC 0x1064a40                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
Thread 1 "report_issue" received signal CUDA_EXCEPTION_14, Warp Illegal Address.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
[Switching focus to CUDA kernel 1, grid 3, block (16423,0,0), thread (0,0,0), device 0, sm 0, warp 5, lane 0]
0x0000000001064b50 in void cuZFP::cudaDecode3<double, 64>(unsigned long long*, double*, uint3, int3, uint3, unsigned int)<<<(16772,1,1),(128,1,1)>>> ()
(cuda-gdb) bt
#0  0x0000000001064b50 in void cuZFP::cudaDecode3<double, 64>(unsigned long long*, double*, uint3, int3, uint3, unsigned int)<<<(16772,1,1),(128,1,1)>>> ()

**Comment by cayrols** [comment]
@lindstro you are right. CudaMalloc succeeds, the encoding seems to work but not the decode3

**Comment by lindstro** [comment]
Well, I had a suspicion that this could be related to 32-bit integer overflow, but 512^3 * sizeof(double) = 2^30, so there's still some wiggle room.  Moreover, we cannot reproduce these issues on our side, so there's something else at play.

I do see some issues with the CUDA code that will kick in when the number of scalars exceeds 2^32, but you're not there yet.  These issues need to be fixed.

Could you perhaps send us your latest code (with any external dependencies like BLAS removed) and we'll take another look.

**Comment by cayrols** [comment]
I have made the simplest example I could do while keeping the bug.
Please find it in the attachment.

Two options to use it (detailed using -h): 
-x the size of the cube
-v the value of compression on the GPU

I have found other parameters that also raise some errors.
Note that, I am using the macro CUDA_ZFP_RATE_PRINT

When I do 
for i in 8 16 32 ; do ./report_issue -x 500 -v $i; done >issue_gpu_diffVal.log

I got an error for a value of 32.
I then run 
for i in $(seq 17 24); do ./report_issue -x 500 -v $i; done >issue_gpu_diffVal_17-24.log
and I found that I starts getting some errors is when the parameter is 18.

Hope this can help.
[report_issue.c_v3.log](https://github.com/LLNL/zfp/files/3794467/report_issue.c_v3.log)
[issue_gpu_diffVal.log](https://github.com/LLNL/zfp/files/3794468/issue_gpu_diffVal.log)
[issue_gpu_diffVal_17-24.log](https://github.com/LLNL/zfp/files/3794469/issue_gpu_diffVal_17-24.log)

**Comment by lindstro** [comment]
I simply cannot reproduce these problems:

% cuda-memcheck ./report_gpu_zfp_issue -x 500 -v 16
========= CUDA-MEMCHECK
[GPU] Rate compression (param 16.000000) on data of size 500x500x500 => 1000000000
========= ERROR SUMMARY: 0 errors
% cuda-memcheck ./report_gpu_zfp_issue -x 500 -v 17
========= CUDA-MEMCHECK
[GPU] Rate compression (param 17.000000) on data of size 500x500x500 => 1000000000
========= ERROR SUMMARY: 0 errors
% cuda-memcheck ./report_gpu_zfp_issue -x 500 -v 18
========= CUDA-MEMCHECK
[GPU] Rate compression (param 18.000000) on data of size 500x500x500 => 1000000000
========= ERROR SUMMARY: 0 errors
% cuda-memcheck ./report_gpu_zfp_issue -x 500 -v 24
========= CUDA-MEMCHECK
[GPU] Rate compression (param 24.000000) on data of size 500x500x500 => 1000000000
========= ERROR SUMMARY: 0 errors
% cuda-memcheck ./report_gpu_zfp_issue -x 513 -v 24
========= CUDA-MEMCHECK
[GPU] Rate compression (param 24.000000) on data of size 513x513x513 => 1080045576
========= ERROR SUMMARY: 0 errors

**Comment by cayrols** [comment]
@lindstro 
Thank you for all your efforts.

I will try to find another machine to test it.

In the meantime, could you send me your cmake log so that I can check if something is missing on my side ?

Thanks

**Comment by cayrols** [comment]
I just installed the code on another machine with cuda 9.1.85 and gcc 4.8.5 and got the same issue.

Could you provide me your CMakeCache.txt so that I can check everything ?
Could you also provide me the output of ldd ?

Which machine do you use ? I could try to have access to it.

**Comment by lindstro** [comment]
[CMakeCache.txt](https://github.com/LLNL/zfp/files/3799368/CMakeCache.txt)

% ldd bin/report_gpu_zfp_issue
	linux-vdso.so.1 =>  (0x00002aaaaaacd000)
	libzfp.so.0 => /g/g19/pl/tmp/zfp/zfp/build/lib64/libzfp.so.0 (0x00002aaaaaccf000)
	libm.so.6 => /lib64/libm.so.6 (0x00002aaaaafe8000)
	libgomp.so.1 => /usr/tce/packages/gcc/gcc-7.3.0/lib64/libgomp.so.1 (0x00002aaaab2ea000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00002aaaab518000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00002aaaab734000)
	librt.so.1 => /lib64/librt.so.1 (0x00002aaaab938000)
	libc.so.6 => /lib64/libc.so.6 (0x00002aaaabb40000)
	/lib64/ld-linux-x86-64.so.2 (0x00002aaaaaaab000)
	libcudart.so.10.1 => /opt/cudatoolkit/10.1/lib64/libcudart.so.10.1 (0x00002aaaabf0e000)
	libstdc++.so.6 => /usr/tce/packages/gcc/gcc-7.3.0/lib64/libstdc++.so.6 (0x00002aaaac18a000)
	libgcc_s.so.1 => /usr/tce/packages/gcc/gcc-7.3.0/lib64/libgcc_s.so.1 (0x00002aaaac50c000)

Unfortunately, I cannot give you access to this machine.

Are we on the same develop branch?  I'm working off the 068f815 commit.

**Comment by lindstro** [comment]
@cayrols FYI, I'm seeing the same behavior on a P100.  The earlier tests were done on a K40m.

**Comment by lindstro** [comment]
Since we cannot seem to reproduce this issue and haven't had anyone else report it, I'm going to close the issue for now.
