### ISSUE TITLE
Rationale for double negation (!!)

### ISSUE THREAD

**Issue by markcmiller86** [LLNL/zfp#76]
Just curious what the rationale is for the double negation, 
https://github.com/LLNL/zfp/blob/068f8150ffc055680fa15c430edb5fed8186bb7c/tests/testzfp.cpp#L434 appearing above and in many other places in this same file?

**Comment by lindstro** [comment]
`!!x` simply means `x != 0`.  Sometimes such comparisons get flagged as a sign mismatch, e.g., `x` is unsigned in this case while `0` is signed.  So then you need `x != 0u` or perhaps even `x != 0ul.`

You might argue that `y = x` would work in this case, but when `y` is a Boolean, this can result in loss of precision compiler warnings when there is no explicit cast.

`!!x` avoids these pitfalls.

**Comment by markcmiller86** [comment]
Hmmm. Never seen or enountered that sort of thing before. Thanks for explanation.

**Comment by lindstro** [comment]
It's a reasonably common idiom in C.  Perhaps less so in C++.  See https://stackoverflow.com/questions/248693/double-negation-in-c-code/248698 for further discussion.
