### ISSUE TITLE
Cert expired

### ISSUE THREAD

**Issue by impredicative** [LLNL/zfp#78]
The https cert associated with the following site has expired:

https://computation.llnl.gov/projects/floating-point-compression

I would personally use a new cert that expires monthly and have an automated process to renew it. This will exercise some automation skills and will eventually prevent the cert from expiring by surprise. Thanks.

**Comment by lindstro** [comment]
Thanks for letting us know.  I've notified those responsible.

**Comment by lindstro** [comment]
Actually, that's a bad link.  The correct one is https://computing.llnl.gov/projects/floating-point-compression.  It appears our README file needs to be updated.

**Comment by lindstro** [comment]
Duh!  This is a result of our department's recent name change from "computation" to "computing."  Anyway, I'll try to chase down all obsolete links.

**Comment by lindstro** [comment]
The deprecated URL now forwards to the new URL.  I'm closing this issue.
