### ISSUE TITLE
CUDA GPU version of zfp

### ISSUE THREAD

**Issue by avolkov1** [LLNL/zfp#8]
The README mentions a CUDA GPU version of zfp in the works. Is there a public version that can be made available of this CUDA GPU version sometime soon?

Thank you

**Comment by mclarsen** [comment]
The experimental CUDA version lives at:
https://github.com/mclarsen/cuZFP
Note that the code and API will be in flux for some time, but currently the implementation support 3D arrays compression and decompression for the types: int32, int64, float32, and float64. There is no documentation, but there are examples in the tests directory.
