### ISSUE TITLE
Question- Sample test Data  (example-seismic ) Info 

### ISSUE THREAD

**Issue by anilbommareddy** [LLNL/zfp#82]
Question 1:
=======
Is any sample test data(example seismic data) or sample test files Info provide to understand and test  on compress and decompress ,to test on OpenMP and ZFP serial stream
example: zfp -f -3 201 201 2412 -r 4 -x serial -i snaps.bin -z test.zfp -h

**Comment by lindstro** [comment]
You may try data sets on [SDR Bench](https://sdrbench.github.io) and [JHTDB](http://turbulence.pha.jhu.edu).
