### ISSUE TITLE
AMD GPU-3D Test Cases Failed like testZfpCuda3dDouble,testZfpCuda3dInt32..

### ISSUE THREAD

**Issue by anilbommareddy** [LLNL/zfp#85]
Cuda source changes are convert into HIP(Hipify). ZFP source changes run in AMD GPU(vega10).

On "make test" command- test cases are executed.

[AMD_ZFP_Trace.zip](https://github.com/LLNL/zfp/files/3891707/AMD_ZFP_Trace.zip)

97% tests passed | 4 tests failed out of 155
Total Test   time (real) = 145.29 sec
The   following tests FAILED: |  
92 -   testZfpCuda3dInt32 (Failed)
95 -   testZfpCuda3dInt64 (Failed)
114 -   testZfpCuda3dFloat (Failed)
117 -   testZfpCuda3dDouble (Failed)

bin]$./testZfpCuda3dInt32
[Traces]
ERROR: Overall compress/decompress test failure

[  ERROR   ] --- [   LINE   ] --- /home/taccuser/Desktop/Anil_Bommareddy/zfp_old_org/tests/src/endtoend/zfpEndtoendBase.c:621: error: Failure!
ERROR: Overall compress/decompress test failure

[  ERROR   ] --- [   LINE   ] --- /home/taccuser/Desktop/Anil_Bommareddy/zfp_old_org/tests/src/endtoend/zfpEndtoendBase.c:621: error: Failure!
ERROR: Overall compress/decompress test failure

[  ERROR   ] --- [   LINE   ] --- /home/taccuser/Desktop/Anil_Bommareddy/zfp_old_org/tests/src/endtoend/zfpEndtoendBase.c:621: error: Failure!
[  PASSED  ] 3 test(s).
[  FAILED  ] 3 test(s), listed below:
[  FAILED  ] given_Cuda_3dInt32ReversedArray_when_ZfpCompressDecompressFixedRate_expect_BitstreamAndArrayChecksumsMatch
[  FAILED  ] given_Cuda_3dInt32PermutedArray_when_ZfpCompressDecompressFixedRate_expect_BitstreamAndArrayChecksumsMatch
[  FAILED  ] given_Cuda_3dInt32Array_when_ZfpCompressDecompressFixedRate_expect_BitstreamAndArrayChecksumsMatch

zfpEndtoendBase.c:621: static void
runCompressDecompressTests(void** state, zfp_mode mode, int numCompressParams)

Please find attached traces

**Comment by lindstro** [comment]
@anilbommareddy Thanks for reporting this.  As an unofficial extension of zfp, I'm not sure we can devote much time to this until we start porting zfp to HIP sometime next year, but knowing that hipify alone is not sufficient is helpful.  Can you please let us know what branch and commit you're working off of?

**Comment by anilbommareddy** [comment]
@lindstro  Thanks for the response and update on ZFP porting.
In fact. we are at developing stage on porting in AMD environment  and working only in the local branch.Once the source changes are testable and it  will be release officially in Git Hub.

**Comment by lindstro** [comment]
FYI, we now have a working HIP implementation on the `feature/hip-support` branch.  We will spend the next few months optimizing and cleaning up the code before officially releasing it.

**Comment by anilbommareddy** [comment]
@lindstro Thanks for the update on ZFP HIP support, I checked the feature/hip-support branch, and below are observations     1.OMP test case failure on enabling HIP                                                                                                                                         command : cmake -DZFP_WITH_OPENMP=ON -DZFP_WITH_HIP=ON -DBUILD_EXAMPLES=ON -DBUILD_UTILITIES=ON -DBUILD_TESTING=ON ..                                                                                                                                                               
 $make build && make test
90% tests passed, 18 tests failed(all omp test cases failed) out of 181
The following tests FAILED:
         79 - testZfpOmp1dInt32 (Failed)              
 2. Scalar(float,int,double) data varaible typecast to  double    (frexp((double)x, &e) _ is  it impact on performance or results?                        https://github.com/LLNL/zfp/blob/feature/hip-support/src/hip_zfp/encode.h

**Comment by lindstro** [comment]
> @lindstro Thanks for the update on ZFP HIP support, I checked the feature/hip-support branch, and below are observations 1.OMP test case failure on enabling HIP command : cmake -DZFP_WITH_OPENMP=ON -DZFP_WITH_HIP=ON -DBUILD_EXAMPLES=ON -DBUILD_UTILITIES=ON -DBUILD_TESTING=ON ..
> $make build && make test
> 90% tests passed, 18 tests failed(all omp test cases failed) out of 181
> The following tests FAILED:
> 79 - testZfpOmp1dInt32 (Failed)

We're aware of this bug and are actively working on determining its cause.  It's good to know that you're seeing the same thing.

> 2. Scalar(float,int,double) data varaible typecast to double (frexp((double)x, &e) _ is it impact on performance or results? https://github.com/LLNL/zfp/blob/feature/hip-support/src/hip_zfp/encode.h

This is not called when Scalar = int, but I agree that we should handle the float case better.  I'm not sure why the cast is even there given the availability of overloads.

@cjy7117 Do you know the reason for this?  It's not in the CUDA version.

**Comment by anilbommareddy** [comment]
@lindstro Thanks for the response.                                                                                                                                                           
      I suspect float data type the function should be "frexpf(float,int* )" and double it should be "frexp(double,int*)". 
         
1.  feature/hip-support branch test case Decompressor Fail : 
./zfp -d -1 630000000 -r 4 -x hip -i /Data/SDRBENCH-NWChem-dataset/acd-tst.bin.d64 -z test.zfp (compressor)
type=double nx=630000000 ny=1 nz=1 nw=1 raw=5040000000 zfp=315000000(compressor) ratio=16 rate=4 -compressor o/p
./ZFP/build/bin# ./zfp -d -1 630000000 -r 4 -x hip -z test.zfp -o test.d64(decompressor)--Fail- Due to Segmentation fault or runtime issue
root cause may suspect in function- void decode_ints( )( zfp/src/hip_zfp/decode.cuh)
File Info:
----------
ARRAY DIMENSION: 1D
number of elements: 
name     size
acd-tst 801098891

In case compressor/decompressor command given parameters are wrong, then behavior expected/response with an error 
but in here compressor success and decompressor fails.

**Comment by lindstro** [comment]
`frexp` should be overloaded based on the scalar type, so there ought not be a need to specialize the code.

Regarding your issue, can it be reproduced using a smaller data set?  Do you observe the same error with other execution policies?  Does the same error occur if you compress and decompress in a single execution (replace `-z test.zfp` on the first command line with `-o test.d64`)?

**Comment by cjy7117** [comment]
@lindstro According to [CUDA Math API](https://docs.nvidia.com/cuda/cuda-math-api/group__CUDA__MATH__SINGLE.html#group__CUDA__MATH__SINGLE) and [HIP Math API](https://rocmdocs.amd.com/en/latest/ROCm_API_References/HIP-MATH.html), frexpf is for float and frexp is for double. The data type conversion was automatically added by the hipify tool since frexp is called and the input data can either float or double.

**Comment by lindstro** [comment]
Right, but there's also an overload `double frexp ( float x, int *nptr )` (see https://rocmdocs.amd.com/en/latest/Programming_Guides/HIP-GUIDE.html#math-functions).  I'm unsure why hipify would force a cast when an overloaded function with matching signature is available when called from a template function.

**Comment by anilbommareddy** [comment]
> `frexp` should be overloaded based on the scalar type, so there ought not be a need to specialize the code.
> 
> Regarding your issue, can it be reproduced using a smaller data set? Do you observe the same error with other execution policies? Does the same error occur if you compress and decompress in a single execution (replace `-z test.zfp` on the first command line with `-o test.d64`)?
error not reproduced with the smaller data set(size 1GB)
Same error not observed in other execution policies like serial.
yes, the same error occurred on compress  in a single execution
Example:./zfp -d -1 630000000 -r 4 -x hip -i /data/SDRBENCH-NWChem-dataset/acd-tst.bin.d64 -o test.d64

**Comment by lindstro** [comment]
To make it easier to track independent issues, I've created a new one.  Please continue this discussion on #123.
