### ISSUE TITLE
CXXLAGS?

### ISSUE THREAD

**Issue by chuckyount** [LLNL/zfp#87]
`cfp/src/Makefile` contains the following link rule:
``` 
$(LIBDIR)/libcfp.so: $(OBJECTS)
      mkdir -p $(LIBDIR)
      $(CXX) $(CXXLAGS) -shared $(SOFLAGS) $^ -o $@
```
Is `CXXLAGS` correct, or should it be `CXXFLAGS`?

**Comment by lindstro** [comment]
@chuckyount Good catch.  I've pushed a fix on the `develop` branch.

Note that on macOS you may have to add `-undefined dynamic_lookup` to `SOFLAGS` (see the `Config` file) when building shared libraries.  For example, `make BUILD_CFP=1 BUILD_SHARED_LIBS=1 SOFLAGS="-undefined dynamic_lookup"`.
