### ISSUE TITLE
slower compression speeds of zfp-0.5.5 compared to v0.5.4

### ISSUE THREAD

**Issue by jvo203** [LLNL/zfp#88]
Hi Peter,

Has anything changed substantially in v0.5.5? It is my impression that compression speeds have dropped compared with the prior v0.5.4. My code uses mutable private views to compress a single 3D cube of float32 in parallel. Each parallel OpenMP task compresses a distinct NxMx4 mutable private view. Basically, on a repeatable basis the new version 0.5.5 seems to take about twice as long compared with v0.5.4. Clearly something must have changed on the ZFP side since my code is exactly the same.

Regards,
Chris

**Comment by lindstro** [comment]
Hi Chris,

The one thing that has changed in 0.5.5 is the default cache size, which now should work better for very "tall" arrays (and for 1D arrays) but might result in smaller caches for square arrays.  I would suggest looking into `set_cache_size` and `cache_size()`.  The latter reports the actual cache size used by a compressed array.  I'd be interested in finding out if the cache size is smaller for your arrays when using 0.5.5 over 0.5.4 and seeing if there's a correlation in speed.

**Comment by jvo203** [comment]
That was fast! Judging by the following code, the cache size is getting set to 0. (It had been a deliberate decision). As per your code comments the cache parameter is "at least csize bytes of cache" so ZFP might be setting it internally to higher values.

zfp::array3f *cube = new zfp::array3f(width, height, depth, 4, NULL, 0);

I will check the values reported by cache_size(). Yes, pressures on the CPU cache etc. might explain the difference.

**Comment by jvo203** [comment]
Indeed the reported cache sizes are way different. The 3D cube in question is 1120 x 1600 x 952, the binary file is about 6.8 GB large.

ZFP 0.5.4 (faster) reports
private_view cache size before (67108864) and after a flush (67108864) bytes

ZFP 0.5.5 (slower) uses
private_view cache size before (2097152) and after a flush (2097152) bytes

Cache sizes are reported from each 1120 x 1600 x 4 mutable private view.

**Comment by jvo203** [comment]
That was it. Doing

zfp::array3f::private_view view(cube, 0, 0, start_k, width, height, depth_k);
view.set_cache_size(67108864);

printf output: private_view cache size before (67108864) and after a flush (67108864) bytes

in version 0.5.5 restores its speed to that of 0.5.4. Thank you!

**Comment by jvo203** [comment]
There is a limit to speed gains. Doubling the cache to ```view.set_cache_size(2 * 67108864);``` has a zero effect on speed.

**Comment by lindstro** [comment]
The cache size and performance relationship tends to be quiet nonlinear.  Especially for multidimensional arrays, you'll often see one or more plateaus in performance.  See Fig 7 in the original zfp paper as an example.

Performance also depends greatly on the memory access pattern.  If at all possible, I would suggest using zfp's iterators to visit the array sequentially in block order.

The reason for changing the default cache size was to address poor performance seen with very tall rectangular arrays and the excessive cache sizes allocated for very wide arrays.  For square arrays, the default cache size is now typically half as large, but the tradeoff is a more reasonable cache size for rectangular and 1D arrays.

**Comment by jvo203** [comment]
OK.
