### ISSUE TITLE
How do I know what's new in each release?

### ISSUE THREAD

**Issue by markcmiller86** [LLNL/zfp#9]
I am updating H5Z-ZFP filter to use latest and greates ZFP library. But, I honestly don't know what is new in the library? Is it just bug fixes or other internal refactoring? Or, are there new features I should be aware of? Where might I go looking to get this information if it already exists? And, if it already exists, any chance future releases might include it in the _releases_ section of this repo?

**Comment by lindstro** [comment]
Release notes are in the VERSIONS text file and http://zfp.readthedocs.io/en/release0.5.2/versions.html.

**Comment by lindstro** [comment]
Great suggestion.  Will do.
