### ISSUE TITLE
Python compression C decompression?

### ISSUE THREAD

**Issue by leventt** [LLNL/zfp#91]
Is it supported to compress in python but decompress in C?

I am serving a compressed stream via python rest api and reading it on browser with emscripten compiled zfp, or at least that is what I am hoping.

My code is here for the C part:
https://github.com/leventt/yakamoz.io/blob/master/zfpHelper.cxx

and here is the python one:
https://github.com/leventt/yakamoz.io/blob/master/main.py (line 128)

Maybe I am doing something obviously wrong as well, my C is rusty :)

Thanks in advance \o/

**Comment by lindstro** [comment]
Yes, this is supported, but you need to be careful to ensure that Python and C array layouts are consistent.  By default, NumPy uses C ordering (rightmost index varies fastest), while zfp assumes Fortran ordering (leftmost index varies fastest).  Try changing the ordering of dimensions to (3, 8320, 120) in your C code.

This can all be done more safely by making use of zfp's header mechanism.  See https://zfp.readthedocs.io/en/release0.5.5/python.html#compression and https://zfp.readthedocs.io/en/release0.5.5/high-level-api.html#c.zfp_write_header.

**Comment by leventt** [comment]
Thanks for the insight \o/

I would also like to contribute emscripten interface for JS when I am done, if it may be helpful to someone. Let me know what the guidelines might be and if all goes well, I will get to it.

**Comment by lindstro** [comment]
Thanks for your offer.  While we're supportive of such an effort, it's unclear at this point that the user base would be sufficiently large that we'd want to incorporate (and therefore commit to maintain) such an interface directly into zfp proper.  For most projects developed outside the core zfp team, we provide links off the [zfp website](https://computing.llnl.gov/projects/floating-point-compression/related-projects).  I'd be happy to do so if you're willing to host and share the code.

PS. Did my suggestion of reversing the array dimensions solve your problem?  If so, I'd like to close out this issue.

**Comment by lindstro** [comment]
Sorry, I didn't see that you already closed the issue.  I assume all is well, then.

**Comment by leventt** [comment]
Fair enough for the contribution information...

For the issue, I don't like to keep it open as I am not actively working to integrate it but only trying to do as my as I can in the free time, while I train my model.

When I tried what you suggested I got an array with all zeros but at this point, I don't want you to waste your time since emscripten also may have some endianness incompatibility.

When I figure things out if you prefer I can open the issue again or create a new one if needed.

**Comment by lindstro** [comment]
I took a closer look at your C code and saw some issues.  You should pass `compressedBytes` to `stream_open`.  The `zfp_flush` call is not needed--it's used only when compressing.  I'm unsure what `fmemopen` and `rread` used for here--I would remove them.  I think with those changes you should be good.

**Comment by leventt** [comment]
Yes! That fixes the 0 bytes :D

Now they are wrong values on emscripten/wasm side :)
I believe the endianness was an issue after-all

Oh well. Thanks for all your generous help. I really appreciate it.

**Comment by lindstro** [comment]
I may have given you bad advice on reversing the dimensions.  Looks like we're already doing that in the Cython code, e.g., `field = zfp_field_3d(pointer, ztype, shape[2], shape[1], shape[0])`.  My apologies.

**Comment by leventt** [comment]
Actually numpy can dump bytes in both orders:
https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.tobytes.html

But decided to move onto trying brotli before coming back to zfp. Let me see if that may be faster for me to implement, for now.

**Comment by lindstro** [comment]
It's true that NumPy supports both C and Fortran order.  It even supports noncontiguous storage, e.g., in the case of slicing.  zfp handles this correctly by examining the strides employed by the ndarray.  The compressed stream has no knowledge about the in-memory representation of the uncompressed array, however.  It's up to the user to specify how the uncompressed array is laid out.  Additionally, the user needs to make sure that the field dimensions agree between compression and decompression.  To facilitate this, zfp can embed this information in a short header, as I previously suggested.  That may in the end be the safest way of using zfp between languages.

Keep in mind that brotli was designed for lossless compression of byte-oriented data.  I would not expect it to be competitive on the type of numerical, spatially correlated data that zfp was designed for.

**Comment by leventt** [comment]
It wasn't comparable to zfp indeed. I will just need to get by before coming back to zfp is my hope. I will bother you more :)
I may ask when I get to it how to create such header from python as it wasn't obvious but I am thinking about making a helper function in C again for python and use pybind11 perhaps. Etiherway that won't be immediate and thanks for your time. I really appreciate your help and code.

**Comment by lindstro** [comment]
The Python part is easy--just pass `write_header = True` to `zfpy.compress`.  Come to think of it, this header is enabled by default, so you must call `zfp_read_header` before `zfp_decompress` in your C code.  Look in utils/zfp.c for an [example](https://github.com/LLNL/zfp/blob/079c409fcb53de5a06fa4336972c04869e33c48d/utils/zfp.c#L554) of how this is done.  This fills in the compression parameters (e.g., the error tolerance) in `zfp_stream` and the array dimensions and scalar type in `zfp_field`.  You just need to call `zfp_field_alloc` (instead of `zfp_field_3d`) to allocate a field struct.

My apologizes again for not knowing our own code better. :)

**Comment by leventt** [comment]
that worked like a charm... let me try that on emscripten side as well :) also I found out that even though I was defining my dtype for numpy array as 32 bit float, results were double according to the header.

**Comment by lindstro** [comment]
Glad to hear it's working.  The zfp scalar type should definitely match the NumPy `dtype`.  Are you certain that the `dtype` of the `ndarray` passed to `zfpy.compress_numpy` is `float32`?  I assume you're calling `zfp_field_type` after `zfp_read_header` to inspect the zfp scalar type.

**Comment by leventt** [comment]
my bad :) I removed the dtype argument at some point. thanks again for all your time \o/

**Comment by lindstro** [comment]
I'm happy to help.  Best of luck with zfp.
