### ISSUE TITLE
Half nyquist freq spectra difference spike

### ISSUE THREAD

**Issue by SoBinary** [LLNL/zfp#93]
If compressing an array of numbers containing a time series wavelet 32bit floats to 16bit fixed rate mode.  If a difference is taken between the original and after compression/decompression the frequency spectrum is perfectly flat (which is great) apart from a minor spike at half nyquist.

Is this an expected feature?

**Comment by lindstro** [comment]
I wouldn't say that it's expected, though the error is weakly spatially correlated, as detailed further in [this paper](https://www.researchgate.net/publication/337322546_A_Collaborative_Effort_to_Improve_Lossy_Compression_Methods_for_Climate_Data).  The error bias correction discussed in the paper is implemented on a [feature branch](https://github.com/LLNL/zfp/tree/feature/unbiased-error).  To use bias correction, you need to enable `ZFP_WITH_UNBIASED_ERROR` at compile-time.  I'd be curious if this solves your problem.

If not, then I could look further into the issue if you're willing to share some data that illustrates the effect.

**Comment by SoBinary** [comment]
That does indeed fix my problem.  I assume this only affects decompression since the checksums of the files compressed with zfp_head and zfp_unbiased are identical but the decompressed file checksums are different.

left is original data, middle is fx display of zfp, right is the zfp unbiased FX
line half way down FX (half nyquist) is what the unbiased fixes
![image](https://user-images.githubusercontent.com/59623590/78170974-a2262700-744b-11ea-8ca7-2246f941dd58.png)

**Comment by lindstro** [comment]
Yes, this affects only decompression.  As an analogy to rounding floating-point numbers, any truncated mantissa bits ought to be replaced with the bit sequence 1000... (or 0111...) to eliminate bias upon reconstruction, assuming the value represented by the truncated bits is uniformly distributed.  Something very similar is done in the unbiased version of zfp, though the correction is applied to zfp's negabinary representation.  Note that the assumption on uniformity holds only for sufficiently high rates.  At low rates, the distribution is closer to Laplace.

I'm glad to hear this addressed your issue and thanks for sharing your results.  Please let me know if I can close out the issue.

**Comment by SoBinary** [comment]
Your help is very much appreciated.  The software is fantastically useful and equally appreciated.
