### ISSUE TITLE
ARM64

### ISSUE THREAD

**Issue by wangyibin0011** [LLNL/zfp#95]
Excuse me, ZFP support ARM64 system？

**Comment by lindstro** [comment]
We have not tested zfp on ARM64, but I see no obvious issues.  If you have access to such a system, I would appreciate any feedback you might be willing to share on your experiences.  I would suggest working off the `develop` branch, which includes extensive testing.

**Comment by lindstro** [comment]
I was able to get access to an ARM64 system.  All tests pass using gcc 4.8.5.
