### ISSUE TITLE
Using memoryviews for decompression

### ISSUE THREAD

**Issue by jakirkham** [LLNL/zfp#96]
Currently decompression requires `bytes` objects [here]( https://github.com/LLNL/zfp/blob/697dd5d96a7fef6d04e4b0fa23f109127e7c587c/python/zfpy.pyx#L332 ) and [here]( https://github.com/LLNL/zfp/blob/697dd5d96a7fef6d04e4b0fa23f109127e7c587c/python/zfpy.pyx#L248 ). This means if users have a `mmap` or other Python object that otherwise acts like an array, they must coerce it to a `bytes` object, which requires a copy. To avoid this it would be better if these functions took a `memoryview` (in particular `uint8_t[::1]`). This would still support a `bytes` object when passed and would still behaving like an array in the code. Most importantly it would allow users to pass these other array-like objects without having to copy to a `bytes` object first.

cc @halehawk @rabernat

**Comment by rabernat** [comment]
Just wanted to leave my 👍 -- this would be a simple change with important performance benefits.

**Comment by jakirkham** [comment]
Also apologies if this is already known to the authors here, but [this doc]( https://cython.readthedocs.io/en/latest/src/userguide/memoryviews.html ) provides some background on using memoryviews in Cython. As Ryan notes this is a simple change (guessing ~4 lines after peaking at the code).

**Comment by lindstro** [comment]
Thanks for the suggestion.  We will look into it and see what can be done.

**Comment by halehawk** [comment]
I know your concern now. But zfp compressed integer, float and double data
to bytes, in what kind of circumstances users will convert the bytes object
to mmap first? @jakirkham @rabernat <https://github.com/rabernat>

**Comment by jakirkham** [comment]
To be clear we are discussing decompression, so its not a `bytes` object being converted an array-like. It's an array-like being converted to `bytes` that's the issue. Second `mmap` is merely one array-like. There are others.

It depends on what `Store` users select in Zarr. If they use LMDB, this would come up for example. Potentially other backends use this. Additionally there has been interest in using memory mapping with directory storage.

Also it depends on what a user's compression/filter pipeline looks like for their data. If there are other steps that come before zfp that produce something else like a NumPy array, this may come up.

The main point here is that users turn to compression (at least in the Zarr case) because memory usage is a concern. So avoiding copies when they are not needed is important to keep memory usage to a minimum.

**Comment by halehawk** [comment]
@lindstro Do you have any update on this issue? "bytes" is not good as a type for passing a buffer, since "In the case that the API only deals with byte strings, i.e. binary data or encoded text, it is best not to type the input argument as something like bytes, because that would restrict the allowed input to exactly that type and exclude both subtypes and other kinds of byte containers, e.g. bytearray objects or memory views." So if we want to assign a numpy array to decompress API, it always has to convert to bytes object first which is not performance efficient with large buffer.
Could you please replace "bytes" at both decompress API with "uint8_t[::1]"? 
I am trying to experiment that in my fork repo, but I don't know how to test with the modification. Could you please point out?
@jakirkham @rabernat

**Comment by jakirkham** [comment]
My guess is @lindstro, et al. would accept a PR @halehawk (if you want to give it a try 😉). My guess is this is a 3 line change.

In case it helps, [`uint8_t` is defined here]( https://github.com/cython/cython/blob/084a25f55d0b4cf8b4c3cd496ec57bb3e2f57f71/Cython/Includes/libc/stdint.pxd#L13 ). So would require a `cimport` from `libc.stdint`. Though one could also just use `unsigned char` if that's easier.

**Comment by jakirkham** [comment]
Would add it looks like [this script contains their CI build process]( https://github.com/LLNL/zfp/blob/0817b0865e13f54af573bf56040fee5869ea4cbd/travis.sh ). Maybe that provides a good starting place for building things locally?

**Comment by lindstro** [comment]
@halehawk Would be great if you could experiment with this and submit a PR.  I assume your question about testing is directed at the numcodecs folks.  If not, the zfpy tests are in `zfp/tests/python` on the `develop` branch.

**Comment by halehawk** [comment]
> My guess is @lindstro, et al. would accept a PR @halehawk (if you want to give it a try 😉). My guess is this is a 3 line change.
> 
> In case it helps, [`uint8_t` is defined here](https://github.com/cython/cython/blob/084a25f55d0b4cf8b4c3cd496ec57bb3e2f57f71/Cython/Includes/libc/stdint.pxd#L13). So would require a `cimport` from `libc.stdint`. Though one could also just use `unsigned char` if that's easier.

Can I use "char *"? Can the return value by ensure_ndarray be passing as a char* to _decompress? Or do I need to get the pointer of the return value?

**Comment by jakirkham** [comment]
Would use `uint8_t[::1]`. That will still accept `bytes` objects, but will also accepts NumPy arrays that are 1-D `uint8`.

**Comment by halehawk** [comment]
@jakirkham @lindstro I am done with the modification, and created a pull
request.

**Comment by jakirkham** [comment]
Guessing that's PR ( https://github.com/LLNL/zfp/pull/106 )? Thanks @halehawk! 😄 Made a couple minor suggestions.

**Comment by halehawk** [comment]
I saw test_numpy failed on some builds, how can I see the error
logs @lindstro

**Comment by lindstro** [comment]
Run `ctest -V` to see the full output.  If the tests pass on your machine but not on Travis, then we might need to run an interactive Travis session to figure out which tests fail.

**Comment by halehawk** [comment]
It passed all tests on my machine. But it failed all your Travis xenial system, so I’d like an error log of it.

**Comment by lindstro** [comment]
I've got the error log on CDash:

```
test_advanced_decompression_checksum (__main__.TestNumpy) ... ERROR
test_advanced_decompression_nonsquare (__main__.TestNumpy) ... ERROR
test_different_dimensions (__main__.TestNumpy) ... ERROR
test_different_dtypes (__main__.TestNumpy) ... ERROR
test_utils (__main__.TestNumpy) ... ERROR

======================================================================
ERROR: test_advanced_decompression_checksum (__main__.TestNumpy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_numpy.py", line 76, in test_advanced_decompression_checksum
    **compression_kwargs
  File "zfpy.pyx", line 249, in zfpy._decompress (/home/travis/build/LLNL/zfp/build/python/zfpy.c:252)
  File "stringsource", line 616, in View.MemoryView.memoryview_cwrapper (/home/travis/build/LLNL/zfp/build/python/zfpy.c:616)
  File "stringsource", line 323, in View.MemoryView.memoryview.__cinit__ (/home/travis/build/LLNL/zfp/build/python/zfpy.c:323)
BufferError: Object is not writable.

======================================================================
ERROR: test_advanced_decompression_nonsquare (__main__.TestNumpy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_numpy.py", line 104, in test_advanced_decompression_nonsquare
    out= decompressed_array,
  File "zfpy.pyx", line 249, in zfpy._decompress (/home/travis/build/LLNL/zfp/build/python/zfpy.c:252)
  File "stringsource", line 616, in View.MemoryView.memoryview_cwrapper (/home/travis/build/LLNL/zfp/build/python/zfpy.c:616)
  File "stringsource", line 323, in View.MemoryView.memoryview.__cinit__ (/home/travis/build/LLNL/zfp/build/python/zfpy.c:323)
BufferError: Object is not writable.

======================================================================
ERROR: test_different_dimensions (__main__.TestNumpy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_numpy.py", line 24, in test_different_dimensions
    self.lossless_round_trip(c_array)
  File "test_numpy.py", line 17, in lossless_round_trip
    decompressed_array = zfpy.decompress_numpy(compressed_array)
  File "zfpy.pyx", line 333, in zfpy.decompress_numpy (/home/travis/build/LLNL/zfp/build/python/zfpy.c:332)
  File "stringsource", line 616, in View.MemoryView.memoryview_cwrapper (/home/travis/build/LLNL/zfp/build/python/zfpy.c:616)
  File "stringsource", line 323, in View.MemoryView.memoryview.__cinit__ (/home/travis/build/LLNL/zfp/build/python/zfpy.c:323)
BufferError: Object is not writable.

======================================================================
ERROR: test_different_dtypes (__main__.TestNumpy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_numpy.py", line 38, in test_different_dtypes
    self.lossless_round_trip(array)
  File "test_numpy.py", line 17, in lossless_round_trip
    decompressed_array = zfpy.decompress_numpy(compressed_array)
  File "zfpy.pyx", line 333, in zfpy.decompress_numpy (/home/travis/build/LLNL/zfp/build/python/zfpy.c:332)
  File "stringsource", line 616, in View.MemoryView.memoryview_cwrapper (/home/travis/build/LLNL/zfp/build/python/zfpy.c:616)
  File "stringsource", line 323, in View.MemoryView.memoryview.__cinit__ (/home/travis/build/LLNL/zfp/build/python/zfpy.c:323)
BufferError: Object is not writable.

======================================================================
ERROR: test_utils (__main__.TestNumpy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_numpy.py", line 186, in test_utils
    compressed_array,
  File "zfpy.pyx", line 333, in zfpy.decompress_numpy (/home/travis/build/LLNL/zfp/build/python/zfpy.c:332)
  File "stringsource", line 616, in View.MemoryView.memoryview_cwrapper (/home/travis/build/LLNL/zfp/build/python/zfpy.c:616)
  File "stringsource", line 323, in View.MemoryView.memoryview.__cinit__ (/home/travis/build/LLNL/zfp/build/python/zfpy.c:323)
BufferError: Object is not writable.

----------------------------------------------------------------------
Ran 5 tests in 17.626s

FAILED (errors=5)
```

**Comment by jakirkham** [comment]
Right, hence my question here ( https://github.com/LLNL/zfp/pull/106#issuecomment-694535340 ).

**Comment by halehawk** [comment]
I got the same errors from my machine tests before I added const to
uint8_t[::1]. But it looks like Xenial needs something different. It looks
like your codes tried to write to a const buffer during decompress process.
Should it only read the decompressed stream?

**Comment by halehawk** [comment]
Could be this reason "Cython always passes the PyBUF_WRITABLE flag to
PyObject_GetBuffer(), even when it doesn't need write access. This causes
read-only buffer objects to raise an exception."

**Comment by halehawk** [comment]
On Fri, Sep 18, 2020 at 10:17 AM Haiying Xu <haiyingx@ucar.edu> wrote:

> Could be this reason "Cython always passes the PyBUF_WRITABLE flag to
> PyObject_GetBuffer(), even when it doesn't need write access. This causes
> read-only buffer objects to raise an exception."
>
> This is solved in cython 0.28, I am using cython 0.29.21. Can we know
which cython version is using on Xenial?

**Comment by lindstro** [comment]
I can't tell from the logs.  You could add a line to travis.sh to find out.

**Comment by halehawk** [comment]
Let me try Buffer object that is used in numcodecs.lzma. But in that case,
I have to add more codes in zfpy.pyx.

**Comment by jakirkham** [comment]
Would take a look at using `fused` types to allow dispatching between `const` and non-`const` variants. Here's [an example in Cython's tests]( https://github.com/cython/cython/blob/8970c94d0c6207133e8fdfac642b1b033b8b4184/tests/errors/fused_types.pyx#L53-L59 ).

**Comment by jakirkham** [comment]
Closing now that PR ( https://github.com/LLNL/zfp/pull/106 ) is in.
