### ISSUE TITLE
ZFP end to end test cases

### ISSUE THREAD

**Issue by arjunshetty955** [LLNL/zfp#97]
I'm interest ZFP to understand a compressor and decompressor techniques in scientific computing
In ZFP is any uses cases or end to end test cases or applications using ZFP to understand compressor/ decompressor techniques,
I think ZFP run  both CPU and GPU. 

Test data or sample data not able to download in reference link or website:-https://sdrbench.github.io/
shown error site cannot reached on select data in  https://sdrbench.github.io/

**Comment by lindstro** [comment]
I'm having a difficult time understanding your first question.  If you're asking for example use cases of zfp, you may find some in the presentations and papers off our [website](https://computing.llnl.gov/projects/floating-point-compression/publications), as well as the many [papers that cite zfp](https://scholar.google.com/scholar?oi=bibs&hl=en&cites=2496609287758472133&as_sdt=5).  If the question is merely whether zfp runs on both the CPU and GPU, then the answer is yes; zfp provides a CUDA execution policy.

Regarding the second issue, the zfp team does not maintain SDRBench.  I would suggest contacting the [CODAR team](mailto:codar-reduction@cels.anl.gov) with any issues you're having with downloading data.

**Comment by lindstro** [comment]
@arjunshetty955 I'd like to close this issue if my answer addresses your question.

**Comment by arjunshetty955** [comment]
@lindstro yes, your answer addressed to my question. kindly close this issue.
